### ISSUE TITLE
Missing database tables in ext_tables.php

### ISSUE THREAD

**Issue by koehlersimon** [FriendsOfTYPO3/tt_address#10]
At least tx_addressgroups_group is missing, wich results in an error while upgrading tt_address from older versions

**Comment by bmack** [comment]
Hey simon,

we have an upgrade wizard from tt_address_group to sys_category but tx_addressgroups_group belongs to a very old version, or am I missing something?

**Comment by bmack** [comment]
Any feedback? Otherwise I will close this ticket in a few days.

**Comment by BastianBalthasarBux** [comment]
A few days later ... :D
