### ISSUE TITLE
Drop old plugin

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/tt_address#104]
* remove from settings
* remove code itself
* remove update wizard 2 versions later

**Comment by christophlehmann** [comment]
It would be nice to keep the Update wizard for legacy plugins added in #125 since updating installations with steps like "Install tt_address 4.0 first to be able to run the update wizard and then use the latest version" are not cool. Just as a side note.

**Comment by georgringer** [comment]
absolutly correct!

**Comment by georgringer** [comment]
I am removing everything with version 5.0 cause I want to get rid of all.
