### ISSUE TITLE
Translation of single addresses only works with original and translated address

### ISSUE THREAD

**Issue by tillschweneker** [FriendsOfTYPO3/tt_address#117]
## Bug Report

**Current Behavior**
When translating a plugin content element with a translated address (in single address mode), the address is not shown in the translated frontend. It only works when the original **and** translated single addresses are chosen.

Furthermore addresses from different languages can be chosen via the search box. 

**Expected behavior/output**
When using the translation feature of TYPO3 the translated address should be visible automatically, without adding the original and translated address.

The search feature should only suggest addresses in the current language.

**Environment**
- TYPO3 version(s): 9.2.2-dev
- tt_address version: 4.0.0 – commit ca78158
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
I guess you are using TYPO3 9.5.2-dev?

**Comment by tillschweneker** [comment]
Oh, sorry. Yes, that was a typo. The bug occurs in 9.5.1, too, though.

**Comment by georgringer** [comment]
wanna test feature branch https://github.com/FriendsOfTYPO3/tt_address/tree/feature/overlay ?

**Comment by georgringer** [comment]
solved
