### ISSUE TITLE
Translation of categorized/folder-based addresses does not work with content fallback

### ISSUE THREAD

**Issue by tillschweneker** [FriendsOfTYPO3/tt_address#119]
## Bug Report

**Current Behavior**
When having a tt_address plugin which shows addresses selected by category and neither the category, nor the address itself is translated, the fallback to the default language does not kick in. It only shows the addresses that are translated.

The same issue is present when the addresses are selected by folder.

**Expected behavior/output**
When content fallback is active the addresses from the default language should be shown.

**Environment**
- TYPO3 version(s): 9.5.2-dev
- tt_address version: 4.0 7dd7f45

**Comment by tillschweneker** [comment]
@georgringer you mentioned testing the feature branch. I'm happy to help testing. What should I test?

**Comment by georgringer** [comment]
@tillschweneker the feature branch has been merged in the meantime.
