### ISSUE TITLE
Trouble rendering image from tt_address record in Typo3 7.6.5 LTS

### ISSUE THREAD

**Issue by manfredwurz** [FriendsOfTYPO3/tt_address#12]
Hi,

I upgraded a typo3 Installation of mine for 4.5.x to 7.6.5. I am rendering tt_address objects within a page, showing the associated image. In 4.5.x this worked fine with the following typoscript:

SNIPPET:

  10 = IMAGE
  10.file.import = uploads/pics/
  10.file.import.field = image
  10.file.import.listNum = 0
  10.file.width = {$content.tt_address.image.width}
  10.wrap = <td valign="top">|</td>

Now, this doesn't render anything useful anymore. I think, the image is no longer located in the tt_address table (using tt_address 3.0.3), but somehwere else.

Can you help and explain, how to render the image from tt_address records now?

Thanks in advance, Manfred

**Comment by BastianBalthasarBux** [comment]
tt_address version 3.x switched to FAL, as well as TYPO3 since version 6.0 (AFAIR, but at least since 6.2)!
Therefore you need to use the TypoScript Code for rendering images from FAL.
See here: https://wiki.typo3.org/File_Abstraction_Layer

**Comment by manfredwurz** [comment]
Thanks for responding and the link!
