### ISSUE TITLE
tt_address displayMode extended in TCEFORM needs to extend default fluid "List.html" template, own templates not recognized from Typoscript configuration 

### ISSUE THREAD

**Issue by RonMen** [FriendsOfTYPO3/tt_address#122]
Hi there.

I added a new ```displayMode```, but need to extend the default template wit a new condition for it to get it running.

**TCEFORM extended**
```
TCEFORM {
    tt_content {
        pi_flexform {
            ttaddress_listview {
                sDISPLAY {
                    settings\.displayMode.addItems {
                        100 = A new view
                    }
                }
            }
        }
    }
}
```

**Typoscript constants extended**
```
plugin.tx_ttaddress {
    view {
        # cat=plugin.tx_ttaddress/file; type=string; label=Path to template partials (FE)
        partialRootPath = fileadmin/Resources/Private/Partials/Tt_address-LTS-9/
        # cat=plugin.tx_ttaddress/file; type=string; label=Path to template layouts (FE)
        layoutRootPath = fileadmin/Resources/Private/Layouts/Tt_address-LTS-9/
    }
}
```

**Current Behavior**
The ```partialRootPath``` is recognized and is working well, but the ```layoutRootPath``` is not recodnized..

**Expected behavior/output**
The ```layoutRootPath``` should be recodnized.

**Environment**
- TYPO3 version: 9.5.1
- tt_address version: 4.0.0 (download 2018-12-07)
- Is your TYPO3 installation set up with Composer (Composer Mode): no

Regards
R.

**Comment by georgringer** [comment]
Of course, you need to adopt the template with a condition so I don't see this as a bug (but will change default templates a bit).

Regarding `layouts`: How does your setup look in the TypoScript ObjectBrowser for `plugin.tx_ttaddress.view.layoutRootPaths`?

**Comment by RonMen** [comment]
Hey Georg,

here is teh screenshot of the TypoScript ObjectBrowser.
![tt_address_typoscript_opject_browser](https://user-images.githubusercontent.com/2003172/49683923-8d8e8480-facc-11e8-99a7-59101d13180b.jpg)

All seems right for me, but I needed to ad the condigition in the main ```tempates``` file direct within the extension folder, it is not working from the fileadmin folder, that is the issue. For ```partials``` the files are recognized from the folder in fileadmin.

Regards
R.

**Comment by Patta** [comment]
I can confirm, that it is not possible to override the `List.html` template with a custom one.

Page TsConfig:
```
TCEFORM{
    tt_content {

        // customize tt_address display mode
        pi_flexform {
            ttaddress_listview {
                sDISPLAY {
                    settings\.displayMode{
                        removeItems = list, single
                        addItems {
                            contact = Contact
                        }
                    }
                }
            }
        }
    }
}
```

Setup:
```
plugin.tx_ttaddress {
    view {
        templateRootPaths {
            0 = EXT:tt_address/Resources/Private/Templates/
            1 = EXT:site_package/Resources/Private/Templates/Extensions/TtAddress/
        }
     }
    ...
}
```

The custom `List.html` template in `EXT:site_package/Resources/Private/Templates/Extensions/TtAddress/` contains:
```
<f:layout name="Default"/>

<f:section name="main">
    <f:render section="displayMode_{settings.displayMode}" arguments="{_all}" />
</f:section>

<f:section name="displayMode_contact">
    <f:for each="{addresses}" as="address" iteration="iterator">
        <f:render partial="Contact" arguments="{_all}" />
    </f:for>
</f:section>
```
The `displayMode_contact` section works only if it is added to the original `List.html` template in `EXT:tt_address/Resources/Private/Templates/`.

**Comment by georgringer** [comment]
Sorry @Patta I can't reproduce that, using 9.5 and tt_address master and having your TsConfig and the following TS 
```
plugin.tx_ttaddress {
    view {
        templateRootPaths {
            0 = EXT:tt_address/Resources/Private/Templates/
            1 = fileadmin/templates/extensions/tt_address/Templates/
        }
     }
}
```

And the file `fileadmin/templates/extensions/tt_address/Templates/Address/List.html` with the content:
```
<f:layout name="Default"/>

<f:section name="main">
    <f:render section="displayMode_{settings.displayMode}" arguments="{_all}" />
</f:section>

<f:section name="displayMode_contact">
    <h4>content section</h4>
</f:section>
```

result: this will render the `<h4>content section</h4>`

**Comment by georgringer** [comment]
Thanks for your feedback!
the subfolder is required as `Address` stands for the `AddressController`. This is how ExtBase works for several years.
