### ISSUE TITLE
Solution to migrate pi1 to extbase

### ISSUE THREAD

**Issue by Patta** [FriendsOfTYPO3/tt_address#125]
Currently it is not possible to migrate from the v3.2 pi1 to the new v4.0 extbase plugin without touch every content element. In a project i have a lot of pages with different views and layouts of addresses.
There is no way to switch to the new plugin without lost the definied address record(s) and layout/displaymode.

See this:
![screenshot](https://user-images.githubusercontent.com/2151127/49930225-72ed4e80-fec4-11e8-8d08-7604e982ea6e.png)

Is there a plan to develop a update wizard for the flexforms?

Many thanks for your work and feedback!

**Comment by georgringer** [comment]
You can enable the (deprecated) pibase plugin to have this still available. but yes currently there is no wizard for that. however would be nice have that available
