### ISSUE TITLE
Missing or wrong image with TYPO3 8.7.22 and legacy plugin

### ISSUE THREAD

**Issue by Patta** [FriendsOfTYPO3/tt_address#127]
## Bug Report

**Current Behavior**
As in some previous issues, no or incorrect images are loaded.

**Expected behavior/output**
The correct image is loaded.

**Environment**
- TYPO3 version(s): 8.7.22
- tt_address version: 4.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10 1803 (local)

**Possible Solution**
Change image file.import.data on line `432` in `Classes/Controller/LegacyPluginController.php` from `'data' => 'file:current:uid_local // file:current:uid'` to `'data' => 'file:current:uid'`

**Additional context**
This was only tested with TYPO3 8.7.22.

**Comment by georgringer** [comment]
Related: #66 && #41
