### ISSUE TITLE
Wrong namespace: No class named TYPO3\TtAddress\Hooks\RealUrlAutoConfiguration

### ISSUE THREAD

**Issue by timkarliczek** [FriendsOfTYPO3/tt_address#128]
## Bug Report

**Current Behavior**
I get the following error in the frontend when EXT:realurl  with auto configuration is enabled:

> No class named TYPO3\TtAddress\Hooks\RealUrlAutoConfiguration

**Expected behavior/output**
In ext_localconf.php a hook for the realurl configuration is registered:
```php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/realurl/class.tx_realurl_autoconfgen.php']['extensionConfiguration']['tt_address'] =
        'TYPO3\\TtAddress\\Hooks\\RealUrlAutoConfiguration->addTtAddressConfig';
```
A class with this namespace does not exist anymore. So the auto configuration can not find the class.

**Environment**
- TYPO3 version: 8.7.21
- tt_address version: 4.0.0
- realurl version: 2.4.0 (`basic.enableAutoConf` must be enabled and no realurl_autoconf.php must exist, the error occurs when realurl generates the new realurl_autoconf.php file)
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
Change hook registration in ext_localconf.php to
```php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/realurl/class.tx_realurl_autoconfgen.php']['extensionConfiguration']['tt_address'] =
        \FriendsOfTYPO3\TtAddress\Hooks\RealUrlAutoConfiguration::class. '->addTtAddressConfig'
```

**Comment by georgringer** [comment]
thx a lot!
