### ISSUE TITLE
Missing function: Localize records

### ISSUE THREAD

**Issue by EvelynGreen511** [FriendsOfTYPO3/tt_address#13]
Hello,
currently it's not possible to localize records. Is it planned to provide this function?
How it is supposed to handle it currently?

Best regards
Evelyn

**Comment by BastianBalthasarBux** [comment]
Yes, we plan to integrate this wanted feature!

**Comment by mrvoss** [comment]
Is there a timeline on when the localization of tt_address records will be implemented? Is there anything we can do to help?

**Comment by BastianBalthasarBux** [comment]
No timeline yet. 'next week in TYPO3' will contain more information on what is going on ;)

**Comment by mtness** [comment]
In the forge there is a similiar issue which has been redirected here, over there is a patch attached!
https://forge.typo3.org/issues/40425

**Comment by BastianBalthasarBux** [comment]
@mtness did you look at the date of the patch? I fear this is far outdated and impossible to apply ... ;)

**Comment by Mruts** [comment]
take a look at https://github.com/Mruts/community and https://github.com/FriendsOfTYPO3/tt_address/pull/31

have fun ;)

**Comment by Lobster1956** [comment]
Will this localisation feature from: https://github.com/BastianBalthasarBux/tt_address will find the way into this version here ??? and if so ... when is a stable TER Version planed ?

**Comment by dhuf** [comment]
I'll try this for now https://github.com/codesource/typo3-cdsrc_ttaddress_l18n

**Comment by BastianBalthasarBux** [comment]
Addressed in PR #71
