### ISSUE TITLE
Overwriting Storage pid in legacy plugin does not work

### ISSUE THREAD

**Issue by christophlehmann** [FriendsOfTYPO3/tt_address#138]
## Bug Report

**Current Behavior**
Setting a storage page in legacy plugin always selects pid 1

**Expected behavior/output**
The configured storage page should be used

**Environment**
- tt_address version: 4.0.1

**Comment by georgringer** [comment]
Thanks for issue & bugfix. Please switch to the extbase version soon as this will be rather soon dropped
