### ISSUE TITLE
Telephone number too clean?

### ISSUE THREAD

**Issue by createdwithlove** [FriendsOfTYPO3/tt_address#142]
https://github.com/FriendsOfTYPO3/tt_address/blob/1cc3a859ccf53d04d2dba5674d6c6262c35a123d/Classes/Evaluation/TelephoneEvaluation.php#L27

Cleaning up the telephone number is basically a sensible thing.
But it also prevents a logical formatting / structure. (see: https://www.typolexikon.de/zahlengliederung/#Telefonnummern) Here not only the norms count, but also the readability and logic.
Maybe a slightly softer regex would be better, for example: `[^\d\+\s\(\)\/\-]` ?

**Comment by georgringer** [comment]
@BastianBalthasarBux wanna take a look?

**Comment by BastianBalthasarBux** [comment]
Another possibility would be: we make this configureable, with our strong regex by default, and everybody can break features by simply editing that regex ... ;)

**Comment by BastianBalthasarBux** [comment]
And just if someone wonders, why copy-paste of a linked phone-number is a nice feature which has use-cases:
if you have e.g. KDE-Connect installed (which allows for syncing clipboard between computer and mobile), you could surf the website on your desktop, copy the number to you clipboard and paste it to the telephone-app of your phone. Personally I use this several times a day ... ;)

**Comment by createdwithlove** [comment]
I agree as much as possible with @BastianBalthasarBux, but the decision as to how the number is displayed should be up to the designer / customer or not? (For example, there is no filter that forbids anyone to write `Straße` with `ss`, even though that's wrong and really hurts.)

If it's just the problem with `(0)`, then you could either put a clear indication that content between `()` will be deleted or a checkbos, which affects the rendering in the FE, so if only the `()` are deleted or that what stands in between.

Maybe escaping the number is also something that should be left to the client device? I have just tried this: `<a href="tel:+49(0)123/456.78-90">tel</a>`. On iOS, it is completely clean, on Android still the 0 is too much.

**Comment by createdwithlove** [comment]
@BastianBalthasarBux yes, you are right. But I think worrying about is the duty of the designer and not the extension. 
Besides E.164 (technical viewpoint) there is recommandation [E.123](https://en.wikipedia.org/wiki/E.123) which is more presentational. 

A configurable RegEx seems to be the best solution. Thank you.

**Comment by BastianBalthasarBux** [comment]
I had another idea: the default regex still stays stronger, the "own-regex option" still comes, but we add a field "telefonnumber linktext". if empty, this is ignored, if not empty, it will be used as link text.
so you could even add something like "click here to call us" ...

**Comment by BastianBalthasarBux** [comment]
Just because I read through E.123 now, i want to add:
1. no parenthesis in international telephone number format following E.123
2. Microsoft telephone number format (proprietary) still uses parentheses (no idea, why this is mentioned there ...).
Everybody is free to think what he/she wants ... and all people who know me better, do know what I think now ... ;-)

**Comment by georgringer** [comment]
my opinion is a flag: enable regex which is default ON and someone can disable it. advanced users can of course use their own hooks and then apply just their own rules

**Comment by BastianBalthasarBux** [comment]
what do we do, if regex is disabled? just no linking in frontend?
there is no chance to verify, if the input of the users is in any way valid to be linked, or not ...

**Comment by georgringer** [comment]
i would still link it, hey it is up to the integrator to adopt the templates

**Comment by BastianBalthasarBux** [comment]
i do not like the idea of a solution, which breaks basic functionality by simply unchecking a checkbox ...
i opt for the two-fields solution, proposed before. this won't break anything, until someone fiddles with the regex, and if one does this, well, he/she should know what they do then anyways.

**Comment by BastianBalthasarBux** [comment]
the two-fields solution is also backwards-compatible ...

**Comment by createdwithlove** [comment]
I like the idea with the two fields, but there should be two fields for all the other links that create input fields to unify them.
A RegEx that could be defined by constants would be a solution that would occur without db changes and should work in most cases. If anyone wants, he can add the second link text field himself with Flexform.

**Comment by georgringer** [comment]
Sorry no 2 fields, that doesn't make sense by default. If your project needs it, just extend the ext

**Comment by BastianBalthasarBux** [comment]
Ok, so we will have a strong default RegEx, configureable in the extension settings (ext-mgm), and we could add 2 examples of less strong RegEx there in the help-text.

**Comment by BastianBalthasarBux** [comment]
For the records: there was accepted a PR, which modifies RegEx for usage of hyphens, which is a first step in the direction we are aiming to go on this topic here.
