### ISSUE TITLE
Categories with Subcategories Cannot be chosen in AND-Mode

### ISSUE THREAD

**Issue by Schwuuuuup** [FriendsOfTYPO3/tt_address#143]
## Bug Report

**Current Behavior**
We use sys_categories organized in a tree like this:
```
Root
+-Adresses
 +-A
 | +-A1
 | +-A2
 +-B
 +-C
```

All concerning address records are in C some are in A some are in B none are in A and B. Whether there are some in A1 or in A2 seems not to be important.

On one page we want to display those, who are in A and C and on another page we want to display those in B and C.
Both worked in tt_address 3.x but in 4.0.1 the A-AND-C Page is empty, while B-AND-C still works.

A-AND-C works as well, when I deactivate A1 and A2.

I tested it and found, that tt_address translates A-AND-C to A-AND-A1-AND-A2-AND-C. This seems to be the case regardless of settings.recursive in the pi_flexform-XML of the content element.

**Expected behavior/output**
To my understanding there is a field recursive in the tt_content table which controls the interpretation of the starting point (address folder/s) and ther ist settings.recursive which should control if the categories should be searched recursively.
The GUI element "Recursive:" seems to be meant to control whether the starting point should be searched recursively. But it controls the settings.recursive within the pi_flexform.
In fact settings.recursive is used for the starting point but I thought that tt_content.recursive should be used for this.
Anyways: When settings.groupsCombination is set to 0 (AND) the groups set in settings.groups should not be searched recursively.

**Environment**
- TYPO3 version(s): 8.7.24
- tt_address version: 4.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Red Hat Enterprise Linux 6 with additional Repositories from iuscommunity for PHP 7.1

**Possible Solution**
Don't search the categories recursively when AND-Mode is chosen or introduce a new setting to switch recursive category search on or off.

**Comment by Schwuuuuup** [comment]
Additional thought:
When A has sub categories, A AND B should be resolved to (A OR A1 OR A2) AND B

**Comment by derhansen** [comment]
IMO the category selection should be implemented like in ext:news. This would allow fine grained control of which tt_address records should be included.

**Category Mode:** 
* Don`t care
* AND
* OR
* NOT AND
* NOT OR

**Category Selection** 
* 1-n categories form TYPo3 category tree

**Include subcategories** 
* Boolean value

Currently, subcategories are always resolved and taken into account (either with AND or OR), so it is e.g. not possible to select tt_address records, which have assigned to a category which has subcategories.
