### ISSUE TITLE
Number of items to be displayed is not working

### ISSUE THREAD

**Issue by AnuBN** [FriendsOfTYPO3/tt_address#144]
tt_address plugin do have an option to limit the number of address records in list view `settings.paginate.itemsPerPage`. But setting this option do not have any response in the template. 

**Environment**
- TYPO3 version: 9.5.3
- tt_address version: 4.0.1

**Expected result**
The list view should limit the number of records as mentioned and the pagination accordingly.

**Possible Solution**
_Demand_ model can be adjusted to listen to itemsPerPage and the setting can be passed to List.html
`<f:widget.paginate>` can process itemsPerPage in the template itself.

**Comment by georgringer** [comment]
Thanks for the report. fixed now
