### ISSUE TITLE
Missing Functionality: Multiple Address, email, Phone

### ISSUE THREAD

**Issue by dextar1** [FriendsOfTYPO3/tt_address#15]
Hi,

This ext would be better if it includes multiple address like personal and work and same goes for phone and email.

**Comment by dextar1** [comment]
i will take some free time and will develop it

**Comment by BastianBalthasarBux** [comment]
After a short discussion with Benni and me, we suggest the way to go as follows: make your own extension for that. your own extension can have a 1:n relation to tt_address records, or if you are really fancy about relating addresses to other kinds of data, you could do it also with a n:n relation.
We clearly say: tt_address is strictly bound to the storage and display of address-records. relating them to 'users' or 'corporations' or other different kinds of data is out of scope of this extension.
regards from awesome T3CON16 in Munich!
