### ISSUE TITLE
Unknown column 'tt_address.single_selection' in 'order clause'

### ISSUE THREAD

**Issue by Patta** [FriendsOfTYPO3/tt_address#156]
## Bug Report

**Current Behavior**
A uncaught TYPO3 exception appears in the frontend, if the `Sort By` option `Order of single addresses` (singleSelection) is selected.

**Expected behavior/output**
Sort the items like in the `singleRecords` field (like default option).

**Environment**
- TYPO3 version(s): 8.7.24
- tt_address version: 4.1.0
- Composer Mode: yes
- OS: Win 10 (local)

**Possible Solution**
none

**Additional context**
There might be a bug in the flexform. The `sortyBy` option `single` has no value and no function if it is selected.
![tt_address-4 1 0_bug_sortby](https://user-images.githubusercontent.com/2151127/52275510-0a64a000-2950-11e9-9544-b08f29b7e7b5.jpg)

**Comment by Schwuuuuup** [comment]
I think there is a missing check whether it should be sorted at all.
in Line 86 of AddressRepository.php
` $query->setOrderings([$sortBy => $order]);`
should be changed to
`
if($sortBy !== 'singleSelection') {
	      $query->setOrderings([$sortBy => $order]);
	    }
`

**Comment by Schwuuuuup** [comment]
Hi,
will there be a release any time soon? 
Our internal development is on hold, as long there is no official version of tt_address 4.x without this bug.
Or is it best do remove the integration of 4.x from our templates for now?

**Comment by georgringer** [comment]
Just use Dev master? I try release in next 2 weeks

**Comment by Schwuuuuup** [comment]
Hey thanks for the quick response. Unfortunately it's not that easy - but that's on our side.

2 weeks are ... well manageable.

Thanks for the good work.

**Comment by Schwuuuuup** [comment]
> I try release in next 2 weeks
That was a month ago... Would be nice to have 4.1.1+ soon

**Comment by georgringer** [comment]
4.2. Has releases long ago

**Comment by Schwuuuuup** [comment]
It's not on TER, that's where our customers are looking for it. (https://extensions.typo3.org/extension/tt_address/)

I know, all the extensions want to move to composer, but that model does not work for everybody (yet - we're working on it, but universities are really big, complicated and slow to move)

**Comment by georgringer** [comment]
@bmack can you publish it to ter?

**Comment by georgringer** [comment]
@Schwuuuuup it should be no in TER, sorry . yes composer is the way to go but we still do TER releases ;) next time pls open a new issue about missing release thx
