### ISSUE TITLE
Introduce allowLanguageSychronization

### ISSUE THREAD

**Issue by derhansen** [FriendsOfTYPO3/tt_address#160]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When translating tt_address records, some fields usually are the same for all languages (e.g. firstname or gender)

**Describe the solution you'd like**
Add `allowLanguageSynchronization` to TCA for those fields would resolve the problem

**Comment by georgringer** [comment]
Yeah go-ahead

**Comment by georgringer** [comment]
Solved
