### ISSUE TITLE
TypoScript setting hidePagination has no effect

### ISSUE THREAD

**Issue by responseinformationsdesign** [FriendsOfTYPO3/tt_address#167]
## Bug Report

**Current Behavior**
TypoScript setting hidePagination has no effect

**Environment**
- TYPO3 version(s): 8.7.24
- tt_address version: 4.1.0

Setting value through flexform works as exspected.

**Comment by georgringer** [comment]
Is setting added to overrideFlexformSettingsIfEmpty as well?

**Comment by responseinformationsdesign** [comment]
Adding "hidePagination" to "overrideFlexformSettingsIfEmpty" made no difference.

**Comment by georgringer** [comment]
solved now
