### ISSUE TITLE
Update Schema Error Message if Custom Fields are added

### ISSUE THREAD

**Issue by KonstantinSoelch** [FriendsOfTYPO3/tt_address#182]
## Bug Report

**Current Behavior**
I have added 2 custom fields to the `tt_address` table.

```
CREATE TABLE tt_address (
 position mediumtext,
 professional_background mediumtext,
 specialization mediumtext,
);
```

Then i tried to run the Database Migration so the fields would be added to the database, but i only get the error message `There is no column with name 't3ver_oid' on table 'tt_address'.`. As soon as i remove my custom fields from the `ext_tables.sql` the Database Migration works again.

Tested the behaviour on CLI and TYPO3 Backend.

**Environment**
- TYPO3 version(s): 9.5.4
- tt_address version: 4.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: MAC OS 10.14 (18A391)
- PHP Version: 7.2

**Comment by georgringer** [comment]
have you added tt_address as dependency to your ext?

**Comment by KonstantinSoelch** [comment]
Not yet, should i?

**Comment by KonstantinSoelch** [comment]
Tried it by adding `"friendsoftypo3/tt-address": "^4.1"` to my composer.json of my templating package and adding:
```
'depends' => array(
            'typo3' => '8.7.0-8.7.99',
            'tt_address' => '4.0.0-4.99.99',
        )
```

Error still carries on

**Comment by georgringer** [comment]
you need to regenerate the `packagestates.php` file, either by manually editing it and sort your package after tt_address or if typo3_console is setup properly with `composer dump-autoload` or by activating any extension.
