### ISSUE TITLE
Autoloader Data gets corrupted when installing tt_address

### ISSUE THREAD

**Issue by Schwuuuuup** [FriendsOfTYPO3/tt_address#197]
Hi,

I'm posting this as a support question because it's a bit of a weird behavior.
Whenever I install tt_address 4.x over tt_address 3.x - or, for that matter install tt_address 3.x over tt_address 4.x, there is a high probability that the autoload data of that particular TYPO3 instance gets corrupted, the website goes down and the user is locked out from the backend.

As a university we have many de-centralized instances of TYPO3. All following one template but are governed by different institutions.
So I do not have direct influence on what the local admins are doing. They do not have access to the install tool though. So sometimes they do Extension updates - as they should - but then they get locked out.

This happens rarely from time to time, but with tt_address it happens almost(!) every time. I have to admit, that I did not analyse this behavior deeply. Therefor this is more a question, why it could be that tt_address is more prone to this problem than other extensions.

The most frequent things that happen are
 * Local Admin ignores my warning and upgrades to 4.1.0 
 * Website crashes
 * I clear the autoloader data, log into the backend and downgrade to 3.x
 * Website crashes again.

So it could well be the change of the major version ...

**Comment by georgringer** [comment]
The issue tracking is not meant as support area, maybe slack is the better thing. I am missing a lot of information in your report: 

- The actual error you get
- the used core version.
- how do the admins update the extension? via extension manager or via FTP?
 
In general you should think about switching to composer based version

Does the site work if you recreate the autoload information in the install tool?

**Comment by Schwuuuuup** [comment]
Hi,
I am on slack (username schwuuuuup as well), but not very familiar with it. I joined the tt_address channel, so if I ask my question there again, just tell me.

Meanwhile, I post the missing information here:
- We're using the latest Version of the TYPO3 8 Branch, so 8.7.24 at the moment.
- The recreation of the autoloader information from the install tool works. Acually thats what I meant by "I cleared the autoloader data" I misspoke there.
- The versions get installed via extension manager.
- Composer based installs are no solutions for us right now, due to the quasi-independence of the installs. (Simplified) The admins do not have access to the install tool nor the system nor the files (via ftp) but must be able to install extensions. It's a a big thing because we are a in-house provider of a university and are not allowed to restrict the institutions but have to provide TYPO3 and other services to people who are not trained webmasters. (it's all a big thing better not tampered with.) We try to change this with TYPO3 9 later this year.

The actual error I get in TYPO3's log file is:

Wed, 13 Mar 2019 16:36:04 +0100 [WARNING] 
request="d0411e756ef72" 
component="TYPO3.CMS.Core.Utility.ExtensionManagementUtility": TYPO3\CMS\Core\Category\CategoryRegistry: 
no category registered for table "pages". Key was already registered. 

Wed, 13 Mar 2019 16:36:04 +0100 [WARNING] 
request="d0411e756ef72" 
component="TYPO3.CMS.Core.Utility.ExtensionManagementUtility": TYPO3\CMS\Core\Category\CategoryRegistry: 
no category registered for table "sys_file_metadata". Key was already registered. 

Wed, 13 Mar 2019 16:36:04 +0100 [WARNING] 
request="d0411e756ef72" 
component="TYPO3.CMS.Core.Utility.ExtensionManagementUtility": TYPO3\CMS\Core\Category\CategoryRegistry: 
no category registered for table "tt_content". Key was already registered.

**Comment by bmack** [comment]
I can reproduce this error message, but this isn't related to tt_address I'd say.

**Comment by Schwuuuuup** [comment]
> I can reproduce this error message, but this isn't related to tt_address I'd say.

I agree, but it happens with tt_address way more often.

When we switched to TYPO3 6.2 back then, we had massive problems with local admins doing extension updates and crashing their instances. Fortunately this went away with TYPO 7.6.
Now it is back, but almost(!) only with tt_address switching major version.

It is not a big deal really, because that does not happen very often I guess, but I wonder why it happens.

**Comment by Schwuuuuup** [comment]
Sorry for not replying earlier, 
I have a screenshot of the error message:
[https://i.imgur.com/4UhrKEL.png](https://i.imgur.com/4UhrKEL.png)

Whenever I update I now avoid the problem by first deactivating tt_address then updating and reactivating it afterwards

**Comment by georgringer** [comment]
I am closing this issue nevertheless, never have seen it in the wild anymore and issue is really old
