### ISSUE TITLE
Update wizard missing in 6.2.17

### ISSUE THREAD

**Issue by andre-spindler** [FriendsOfTYPO3/tt_address#2]
On a typo3 6.2.17 (php 5.5.31), the update wizard for address groups is missing.

The update wizard for images is included and works as it should do.
But the one for migrating address groups is missing at all.

Reason is not a bug in the updater, but a bug when including it in ext_localconf.php, as the same hook is used twice and the second one overrides the first. The keys have just to be made unique:

```
// Update scripts
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update']['tt_address_group'] = 'TYPO3\\TtAddress\\Updates\\AddressGroupToSysCategory';
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/install']['update']['tt_address_group'] = 'TYPO3\\TtAddress\\Updates\\ImageToFileReference';
```

**Comment by bmack** [comment]
Fixed in the next release
