### ISSUE TITLE
no labels for sortBy [default] and [sorting] in BE

### ISSUE THREAD

**Issue by rtoenjes** [FriendsOfTYPO3/tt_address#201]
*The first two elements in plugin options Sort By have no label*

**Environment**
- TYPO3 version(s): 9.5.4
- tt_address version: 4.1.0
- Composer Mode: no

**Possible Solution**
 As a quick fix I added them via typoscript:
```
TCEFORM {
  tt_content {
    pi_flexform {
      ttaddress_listview {
        sDEF {
          settings\.sortBy {
            altLabels {
              default = Default
              sorting = Sorting
            }
          }
        }
      }
    }
  }
}
```

**Comment by Patta** [comment]
I can confirm this even with the latest 4.2.0 release.

**Comment by georgringer** [comment]
thanks for the issue, it is fixed now
