### ISSUE TITLE
Argument 1 passed to FriendsOfTYPO3\TtAddress\Controller\AddressController::removeDots() must be of the type array, null given, called in /usr/www/users/nextest2/zeva.org/typo3conf/ext/tt_address/Classes/Controller/AddressController.php on line 85

### ISSUE THREAD

**Issue by ADRNexave** [FriendsOfTYPO3/tt_address#206]
## Bug Report

**Current Behavior**
I created some Contacts and wanted to use them on the page. Then this Error occured when i activate the Plugin with the contact.

**Expected behavior/output**
I expected that the contact is rendered when implementing it on the page.

**Environment**
- TYPO3 version(s): 9.5.5
- tt_address version: 4.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux Debian

![image](https://user-images.githubusercontent.com/49022341/55144903-05e38900-5142-11e9-940c-5cf11475f122.png)
![image](https://user-images.githubusercontent.com/49022341/55144929-17c52c00-5142-11e9-8565-e1f4da3427fa.png)

**Comment by georgringer** [comment]
Did you include the TS? however fill fix the issue

**Comment by ADRNexave** [comment]
I use Templavoilá and cant find the settings to enable the TS for tt_address. Do you have an idea?

**Comment by georgringer** [comment]
Fixed with mentioned issue
