### ISSUE TITLE
date's before 14.12.1901

### ISSUE THREAD

**Issue by morange** [FriendsOfTYPO3/tt_address#209]
## Bug Report

**Current Behavior**
I would like to save dates before 14.12.1901. I became this answer:
"1: These fields of record 9 in table "tt_address" have not been saved correctly: birthday! The values might have changed due to type casting of the database."

**Expected behavior/output**

**Environment**
- TYPO3 version(s): [9.2.5]
- tt_address version: [4.2.0]
- set up without Composer (Composer Mode – no)
- OS: OSX 10.14.4, XAMPP (Apache/2.4.35 (Unix) OpenSSL/1.0.2p PHP/7.2.11 mod_perl/2.0.8-dev Perl/v5.16.3)

**Additional context**
 took over part of the table "tt_address" from another project. Up to the problem with the date before the 14.12.1901 presently no problem.

**Comment by georgringer** [comment]
Will take a look, could also be related to core issue of https://forge.typo3.org/issues/79448

**Comment by morange** [comment]
It could be the same problem. How can i give you or the core team more and better information?
Thx Steffen

**Comment by georgringer** [comment]
I will test in next days, if I can't reproduce it, will come back to you
