### ISSUE TITLE
How to set filter dynamically in plug listview mode?

### ISSUE THREAD

**Issue by baden32** [FriendsOfTYPO3/tt_address#211]
tt_address 4.1.0 is installed, configured and it works fine on my Typo 8.7.24 website.
Using the plugin in "List view" mode works as well with category filtering.

However, I would like to be able to set the category filters **dynamically**, using ie. GET parameters from querystring. 

In other words: is it possible to give parameter at tt_address List view mode to get other results than the one defined in my content block?

**Comment by georgringer** [comment]
This is a feature of 4.2.0, https://github.com/FriendsOfTYPO3/tt_address/blob/master/Documentation/Administration/Changelog/v/4-2-0.rst#allow-overriding-demand-object
