### ISSUE TITLE
Incomplete e-mail address obfuscation in fluid templates 

### ISSUE THREAD

**Issue by Schwuuuuup** [FriendsOfTYPO3/tt_address#212]
## Bug Report

The reference Fluid templates are buit in a way, that circumvents the e-mail obfuscation features of TYPO3
In [Line 53 of Address.html](https://github.com/FriendsOfTYPO3/tt_address/blob/4c2213dc5fa3c2b03667b684cddb9b2a23c73372/Resources/Private/Partials/Address.html#L53), e-mail addresses get linked as:
`<f:link.email email="{address.email}"><span itemprop="email">{address.email}</span></f:link.email>`
By using the LinkEmailViewhelper, the HREF of the link gets encrypted via JS, but the Linked text is the e-mail address itself in plain text.

TYPO3 has the Options `config.spamProtectEmailAddresses` and 
 `config.spamProtectEmailAddresses_atSubst` which are not utilized that way.
The LinkEmailViewhelper generates a protected form of the address when it's called with no content.
So maybe that line should be changed to 
`<span itemprop="email"><f:link.email email="{address.email}" /></span>`

The order of SPAN and A gets reversed that way but I don't think that's a problem.

**Environment**
- TYPO3 version(s): 8.7.24
- tt_address version: 4.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: RHEL6

**Comment by bmack** [comment]
That's right. Seems like we should change the itemprop to be part of the ViewHelper as "additionalAttribute" or put the span outside. @georgringer what's the best way for semantic annotations?
