### ISSUE TITLE
Settings for Frontend integration (Documentation)

### ISSUE THREAD

**Issue by rtoenjes** [FriendsOfTYPO3/tt_address#214]
In https://docs.typo3.org/typo3cms/extensions/tt_address/UsersManual/Maps/Index.html there’s an error for setting the map type. It has to be set via `plugin.tx_ttaddress.settings.map.rendering = googleMaps`.

And the default is `googleMaps`, not `leaflet` as it is defined in `setup.typoscript` (I did a PR).

**Comment by georgringer** [comment]
solved, thx
