### ISSUE TITLE
Error while saving with gender „divers“

### ISSUE THREAD

**Issue by rtoenjes** [FriendsOfTYPO3/tt_address#215]
**Current Behavior**
When saving an address record with gender „divers“ an error appears:
`These fields of record 13 in table "tt_address" have not been saved correctly: gender! The values might have changed due to type casting of the database.` The saved value is `v` but is not displayed in the BE.
The other three possibilities work well.

**Environment**
- TYPO3 version: 8.7.24
- tt_address version: 4.2.0
- Composer Mode: no

**Comment by bihor** [comment]
In the SQL-file the field
gender varchar(1) DEFAULT '' NOT NULL,
should be changed
OR
in the tca-file the line
` ['LLL:EXT:tt_address/Resources/Private/Language/locallang_db.xlf:tt_address.gender.various', 'various'],`
should be changed to
`['LLL:EXT:tt_address/Resources/Private/Language/locallang_db.xlf:tt_address.gender.various', 'v'],`

**Comment by rtoenjes** [comment]
Thanks, good hint, I did a PR for that.

**Comment by georgringer** [comment]
solved
