### ISSUE TITLE
MySQL Error: Index column size too large. The maximum column size is 767 bytes.

### ISSUE THREAD

**Issue by buepro** [FriendsOfTYPO3/tt_address#218]
## Bug Report

**Current Behavior**
Some hosters provide db's configured with utf8mb4 (e.g. utf8mb4_unicode_ci) encoding. When trying to update the db with the needed fields for tt_address the following error comes up:

`Error: Index column size too large. The maximum column size is 767 bytes.`

**Environment**
- TYPO3 version(s): 9.5.6
- tt_address version: 4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Possible Solution**
Change the size from the email field to 191 characters in `ext_tables.sql`:

`email varchar(191) DEFAULT '' NOT NULL,`

**Comment by BastianBalthasarBux** [comment]
The proposed solution is only a quick and dirty workaround for the circumstance you have to deal with an improperly configured Database, but it's not a clean solution to that problem.

Please configure your database properly, so this won't occur.
Hints for you according web research: innodb_large_prefix

Link with some more information: https://stackoverflow.com/questions/35847015/mysql-change-innodb-large-prefix

**Comment by MrManga** [comment]
Same Problem for me, but all the required Options are turned on Oo
Will your suggestion really be the solution leading to success?

For my installation:
innodb_large_preifx: ON
innodb file format: Barracuda
innodb file per table: ON

Maybe you do have any other hints, that would make me using tt_address (and tt_news ... same here)

Thanks.

**Comment by BastianBalthasarBux** [comment]
What's the row_format?

**Comment by MrManga** [comment]
I can't find a setting / variable like row_format for my server (it's hosted by my internet provider, so I expect only a few possibilities to change settings that are necessary to get tt_address working)

![grafik](https://user-images.githubusercontent.com/39707975/62832537-8a85fe00-bc30-11e9-852c-664f24b5e286.png)
