### ISSUE TITLE
recordLinks are not renderd

### ISSUE THREAD

**Issue by morange** [FriendsOfTYPO3/tt_address#220]
## Bug Report

**Current Behavior**
recordLinks are not renderd, the output is like this one: t3://record?identifier=tt_address&uid=265

**Expected behavior/output**
Rendered link to navigate to an address / person. The link should be created as follows:
http://localhost/projekt1/de/ueber-uns/unsere-mitarbeitenden/missionare/detail-missionare?tt_address%5Baction%5D=show&tt_address%5Baddress%5D=265&tt_address%5Bcontroller%5D=Address&cHash=f4378b41145c980a9ab9cdfb5eda55f6

**Environment**
- TYPO3 version: 9.5.6
- tt_address version: 4.3.0
- Composer Mode: no
- OS: macOS 10.14.5

**Possible Solution**
––––––

**Additional context**
If the link is created in a text box that does not use the tt_address extension, the link korrket will be created.

**Comment by georgringer** [comment]
in which field is the link created?

**Comment by morange** [comment]
Hi, in the field "description".
