### ISSUE TITLE
_LOCAL_LANG not supported

### ISSUE THREAD

**Issue by peterkraume** [FriendsOfTYPO3/tt_address#221]
## Bug Report

**Current Behavior**
This code snippet does not work:
```
plugin.tx_ttaddress {
  _LOCAL_LANG.default {
    paginate_next = TEST
    paginate_previous = TEST
   }
}
```

**Environment**
- TYPO3 version(s): 9.7.5
- tt_address version: 4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

This issue was first reported at StackOverflow:
https://stackoverflow.com/questions/56187213/typo3-tx-ttaddress-how-to-change-locallang-of-pagebrowser

**Comment by georgringer** [comment]
As the pagination comes from fluid, the correct TypoScript would be
```
plugin.tx_fluid {
  _LOCAL_LANG.default {
    widget.pagination.next = TEST
   }
}
```

Tested this on a 9.5

**Comment by peterkraume** [comment]
So the labels like `paginate_previous` or `paginate_next` are obsolete and can be removed from `Resources/Private/Language/locallang.xlf`?

**Comment by georgringer** [comment]
I guess those are used by the pibase plugin but after removing that, yes
