### ISSUE TITLE
Sorting including german Umlauts doesn't work correct

### ISSUE THREAD

**Issue by mschmitz89** [FriendsOfTYPO3/tt_address#222]
The alphabetical sorting doesn't work correct with german Umlauts. Umlauts will be appended at last in the list instead of handling it as _ä = a_ or _ä = ae_ which would be correct according to DIN 2007-1.

Example of wrong sorted output:

Bader
Baer
Bogenschütz
Bächle
Bär
Böttcher

Found that in the old pi-based version, this behaviour was already fixed (line 598): https://github.com/TYPO3-extensions/tt_address/blob/master/pi1/class.tx_ttaddress_pi1.php

**Environment**
- TYPO3 9.5.6
- tt_address version: 4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Windows 10

Thank you!

**Comment by mschmitz89** [comment]
Any news to this? :)

Maybe including the old function for this works well?

    /**
     * Removes whitespaces, hyphens and replaces umlauts to allow a correct
     * sorting with multisort.
     *
     * @param mixed $value: value to clean
     * @return cleaned value
     */
    protected function normalizeSortingString($value)
    {
        if (!is_string($value)) {
            // return if value is not a string
            return $value;
        }

        $value = $GLOBALS['TSFE']->csConvObj->conv_case($GLOBALS['TSFE']->renderCharset, $value, 'toLower'); // lowercase
        $value = preg_replace("/\s+/", '', $value); // remove whitespace
        $value = preg_replace('/-/', '', $value); // remove hyphens e.g. from double names
        $value = preg_replace('/ü/', 'u', $value); // remove umlauts
        $value = preg_replace('/ä/', 'a', $value);
        $value = preg_replace('/ö/', 'o', $value);
        $value = preg_replace('/ë/', 'e', $value);
        $value = preg_replace('/é/', 'e', $value);
        $value = preg_replace('/è/', 'e', $value);
        $value = preg_replace('/ç/', 'c', $value);

        return $value;
    }

**Comment by SirRise** [comment]
I added an option in the extension configuration to treat german umlaut characters as their latin counterparts.

https://github.com/SirRise/tt_address-germanUmlautfix

**Comment by SirRise** [comment]
https://github.com/SirRise/tt_address-germanUmlautfix/pull/1

**Comment by georgringer** [comment]
What about using the correct `COLLATE`, see https://stackoverflow.com/questions/17612897/sort-entries-from-mysql-database-in-correct-order-umlauts-are-after-character?

**Comment by SirRise** [comment]
We found that same post too but the issue is that Typo3 doesn't allow you to add a `COLLATE` in addition to the orderings.

**Comment by georgringer** [comment]
You need to define the collate in db

**Comment by BastianBalthasarBux** [comment]
The proposed solution is in fact a dirty hack for not correctly configured databases.
Therefore we will reject that change.
Please really correct collation of your database, including all the tables and fields. If you do not have shell access to that server, you could maybe try to use phpmyadmin or adminer extensions from TER to correct the collations.
Please note, that only changing the collation after data has been inserted already, may break your encodings (and thus your contents). Use iconv or similar methods to convert your contents.
There are plenty of tutorials on the internet explaining how to do that. (it varies also with the real source-encoding and target-encoding you need).

BTW: It is nowadays widely and strongly recommended to switch the whole DB-Server to an utf-8 based collation at least by default. For TYPO3 ATM is recommended utf8mb4, AFAIK.

**Comment by BastianBalthasarBux** [comment]
Small hints on collations and MySQL: https://stackoverflow.com/questions/5526169/what-is-the-best-mysql-collation-for-german-language/48325386#48325386
