### ISSUE TITLE
custom templates not working

### ISSUE THREAD

**Issue by riesemann** [FriendsOfTYPO3/tt_address#233]
## Bug Report

**Current Behavior**
Using a custom template as defined in settings.displayMode doesn't work.

- I created an new displayMode like described in the documents of tt_address.

- Created my own templates, partials, layouts as a copy of the origin extending the .view-array to use them like this:

```
plugin.tx_ttaddress {
    view {
        templateRootPaths {
            10 = EXT:sd_sitepackage/Resources/Private/Templates/Ext/Address/
        }
        partialRootPaths {
            10 = EXT:sd_sitepackage/Resources/Private/Partials/Ext/Address/
        }
        layoutRootPaths {
            10 = EXT:sd_sitepackage/Resources/Private/Layouts/Ext/Address/
        }
    }
}
```
- added a new section (displayMode_carousel) in my List.html like this:
```
<f:section name="displayMode_carousel">
	<f:render partial="Carousel" arguments="{_all}"/>
</f:section>
```

**This results in a fluid-error: "Section "displayMode_carousel" does not exist"**

*Even, if i produce an Error in .../Templates/Ext/Address/List.html - it doesnt't have any effect, if i use e.g. displayMode_map instead*

*I tried also to copy the `plugin.tx_ttaddress.view {...}` in TYPO3s Setup, but it doesn't have any effect.*

**Thanks for your help - and keep up your good work on this!**

**Environment**
- TYPO3 version(s): 9.5.8
- tt_address version: 4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): NO

**Comment by riesemann** [comment]
P.S.
Custom partials and layouts are working as expected.

**Comment by georgringer** [comment]
I believe that this is a misconfiguration as I can't reproduce it.
My TypoScript
```
plugin.tx_ttaddress {
    view {
        templateRootPaths {
            10 = fileadmin/templates/extensions/tt_address/Templates/
        }
        partialRootPaths {
            10 = fileadmin/templates/extensions/tt_address/Partials/
        }
        layoutRootPaths {
            10 = fileadmin/templates/extensions/tt_address/Layouts/
        }
    }
}
```

My Page TsConfig:
```
TCEFORM.tt_content.pi_flexform.ttaddress_listview.sDISPLAY.settings\.displayMode.addItems.carousel = My Carousel
```

and this is a screenshot of the file structure

<img width="573" alt="Bildschirmfoto 2019-09-09 um 20 16 57" src="https://user-images.githubusercontent.com/1905663/64556036-e8485b80-d33e-11e9-80de-6562b642e576.png">

can you recheck your setup? Especially if the `List.html` is here: `EXT:sd_sitepackage/Resources/Private/Templates/Ext/Address/Address/List.html`?

**Comment by riesemann** [comment]
Tripple checked my config according to yours (in a new project).

**TCEFOM.tsconfig:**
TCEFORM.tt_content.pi_flexform.ttaddress_listview.sDISPLAY.settings\.displayMode.addItems.circle = Kreisrund

**setup.typoscript:**
plugin.tx_ttaddress.view {
    templateRootPaths.10 = typo3conf/ext/sd_sitepackage/Resources/Private/Templates/Ext/Address/
    partialRootPaths.10 = typo3conf/ext/sd_sitepackage/Resources/Private/Partials/Ext/Address/
    layoutRootPaths.10 = typo3conf/ext/sd_sitepackage/Resources/Private/Layouts/Ext/Address/
}

**All paths are pointing to the right folders.** 
partialRootPaths.10 is working as expected but templateRootPaths.10 is not used in my case.


```
in /data/typo3/sources/typo3_src-9.5.9/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php line 269
                if ($ignoreUnknown) {
                    return '';
                }
                return $renderingContext->getErrorHandler()->handleViewError(
                    new InvalidSectionException('Section "' . $sectionName . '" does not exist.')
```
```
in /data/typo3/sources/typo3_src-9.5.9/vendor/typo3fluid/fluid/src/ViewHelpers/RenderViewHelper.php line 143
            $content = (new $delegate())->render($renderingContext);
        } elseif ($partial !== null) {
            $content = $view->renderPartial($partial, $section, $variables, $optional);
        } elseif ($section !== null) {
            $content = $view->renderSection($section, $variables, $optional);
        } elseif (!$optional) {
            throw new \InvalidArgumentException('ViewHelper f:render called without either argument section, partial, renderable or delegate and optional flag is false');
        }
        // Replace empty content with default value. If default is
```

**Comment by riesemann** [comment]
I also checked what happens if my List.html is placed in fileadmin:

plugin.tx_ttaddress.view.templateRootPaths.20 = fileadmin/AddressTemplate/

Same problem - the template could not be fetched.

**List.html:**
````html
<f:layout name="Default"/>

<f:section name="main">
	<div class="tt_address_list">
		<f:render section="displayMode_{settings.displayMode}" arguments="{_all}" />
	</div>
</f:section>

<f:section name="displayMode_list">
	<!--TYPO3SEARCH_end-->
	<f:if condition="{settings.hidePagination}">
		<f:then>
			<f:for each="{addresses}" as="address" iteration="iterator">
				<f:render partial="ListItem" arguments="{_all}"/>
			</f:for>
		</f:then>
		<f:else>
			<f:widget.paginate objects="{addresses}" as="paginatedAdresses" configuration="{settings.paginate}">
				<f:for each="{paginatedAdresses}" as="address" iteration="iterator">
					<f:render partial="ListItem" arguments="{_all}"/>
				</f:for>
			</f:widget.paginate>
		</f:else>
	</f:if>
	<!--TYPO3SEARCH_begin-->
</f:section>

<f:section name="displayMode_single">
	<f:for each="{addresses}" as="address">
		<f:render partial="Full" arguments="{_all}"/>
	</f:for>
</f:section>

<f:section name="displayMode_map">
	<f:render partial="Maps" section="{settings.map.rendering}" arguments="{_all}"/>
</f:section>

<f:section name="displayMode_circle">
	<f:render partial="Circle" arguments="{_all}"/>
</f:section>
````

**Comment by georgringer** [comment]
@riesemann Can you please add the paths of your single html files as well?

**Comment by riesemann** [comment]
**Ok, i found it out - there is NO Bug!**

In your TemplatePath the List.html is stored in a subfolder called **Address**
In my case i let the TemplatePath directly point to: `Resources/Private/Templates/Ext/Address/`
The folder structure should be `Resources/Private/Templates/Ext/Address/Address/List.html`


Thank you for asking the right questions!

**Comment by riesemann** [comment]
closed

**Comment by georgringer** [comment]
just for explanation. the subfolder `Address` is because it is the `AddressController`. 

thanks for rechecking and finding the issue
