### ISSUE TITLE
Fluid TypeError wenn using ttaddress_listview plugin

### ISSUE THREAD

**Issue by danielkoch** [FriendsOfTYPO3/tt_address#248]
## Bug Report

**Current Behavior**
I'm using the ttaddress_listview frontend plugin and get the following error:
```
Argument 2 passed to TYPO3\CMS\Core\Utility\ArrayUtility::mergeRecursiveWithOverrule() must be of the type array, null given, called in /typo3_src/typo3_src-9.5.9/typo3/sysext/fluid/Classes/ViewHelpers/Widget/Controller/PaginateController.php on line 74
```
**Expected behavior/output**
tt_address records should be displayed properly without any errors.

**Environment**
- TYPO3 version(s): 9.5.9
- tt_address version: 5.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 10.13.6

**Additional context**
This is the fluid template section that causes the problem: https://github.com/FriendsOfTYPO3/tt_address/blob/master/Resources/Private/Templates/Address/List.html#L18-L22

**Comment by georgringer** [comment]
Is `{settings.paginate}` filled?

**Comment by danielkoch** [comment]
Great. That was the cause. Upgraded from an old version and missed this new configuration part.

**Comment by georgringer** [comment]
thx for feedback, however would be nice to catch the issue in the core, will take care
