### ISSUE TITLE
remove pidList from getSingleRecords()

### ISSUE THREAD

**Issue by SvenJuergens** [FriendsOfTYPO3/tt_address#25]
hi,

maybe it's more a question as an issue.
This is the DB Query for singleRecords

```
            $addresses = $GLOBALS['TYPO3_DB']->exec_SELECTgetRows(
                '*',
                'tt_address',
                'uid IN(' . $uidList . ') ' . (!empty($this->conf['pidList']) ? ' AND pid IN (' . $this->conf['pidList'] . ')' : '')
                . $this->cObj->enableFields('tt_address')
            );
```

why you ask for pidList, uid should be enough as unique identifier. or not?
Problem is, if you don't set a pidList in TS or Flexform the pidList is set to $GLOBALS['TSFE']->id in init()

```
  $pages = $pages ?
            implode(GeneralUtility::intExplode(',', $pages), ',') :
            $GLOBALS['TSFE']->id;
```

so in the DB Query there is always a pidList and you must set the correct pidList if you only want to use singleRecords, it's very confusing for an integrator.

best regards
Sven

**Comment by BastianBalthasarBux** [comment]
Hi @SvenJuergens,
Thanks for reporting, I will have a look at it!

**Comment by bmack** [comment]
This is a principle which is around 15ys old and can be found in a lot of other TypoScript-related logic - still in the core.

The PID is a constraint, especially useful in multisite systems or with large access rights permissions so editors cannot select an address from a different page they do not have access to (esp if you have addresses in different locations). Basically, editors can only add a plugin to a storage folder and to an address they have access to.

**Comment by BastianBalthasarBux** [comment]
Pretty much what I think too, @bmack 
So i will close this issue, as it won't be "solved" for pi-base plugin.
