### ISSUE TITLE
Set description meta tag

### ISSUE THREAD

**Issue by georgringer** [FriendsOfTYPO3/tt_address#254]
Description meta tag could be set to something like 
```
{address.fullName} ☎ {address.phone} ➤ {address.address}, {address.zip} {address.city},{address.country}
```

**Comment by BastianBalthasarBux** [comment]
Just leave out e-mail-address in default configuration ...

**Comment by Patta** [comment]
It would be great, if the open graph meta tag title and description could also be set on the detail/single page.
