### ISSUE TITLE
Editing first/middle/last name does not update combined name field in localized record versions 

### ISSUE THREAD

**Issue by crealistiques** [FriendsOfTYPO3/tt_address#259]
## Bug Report

**Current Behavior**
Assume I have a tt_address record in default language and a localized version, eg. in English language. When I edit and save the default language record with changes in one of the fields first name, middle name or last name, the localized (Englisch) version still contains the old value in the combined name field. 

**Expected behavior/output**
When editing an tt_address record in default language the combined name field should be updated (if neccessary) in all localized versions of the original tt_address record, too.

**Environment**
- TYPO3 version(s): 8.7.27
- tt_address version:  4.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux

**Comment by pulponair** [comment]
Any news here?

**Comment by georgringer** [comment]
didn't have time to look at it, feel free to do so @pulponair

**Comment by hfuonlineservices** [comment]
We have the same issue, but a different environment:

* TYPO3 version: 9.5.13
* tt_address version: 5.0.0
* Is your TYPO3 installation set up with Composer (Composer Mode): yes
* OS: Linux

By adding `l10n_mode' => 'exclude'` to the TCA configuration of `first_name`, `middle_name` and `last_name` changes made in those fields are reflected in the localized record (see https://docs.typo3.org/m/typo3/reference-tca/master/en-us/Columns/Index.html#l10n-mode).

I guess `l10n_mode` should be applied to all fields which have set `'l10n_display' => 'defaultAsReadonly'`. If you like we can provide a PR.

**Comment by georgringer** [comment]
@hfuonlineservices makes sense, yes go ahead
