### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by tlogfred** [FriendsOfTYPO3/tt_address#26]
Hi, sorting with TS is not possible. In class.tx_ttaddress_pi1.php on line 178-187 the parameter $sortOrder gets always the value from the flexform, because the flexformfield "sortOrder" has the default value "ASC". So it would be better to make an empty default value in the flexform, to be able to sort from TS and flexform.

					<sortOrder>
						<TCEforms>
							<label>LLL:EXT:tt_address/pi1/locallang_ff.xml:pi1_flexform.sortOrder</label>
							<config>
								<type>select</type>
								<items type="array">
									<numIndex index="0" type="array">
										<numIndex index="0"></numIndex>
										<numIndex index="1"></numIndex>
									</numIndex>
									<numIndex index="1" type="array">
										<numIndex index="0">LLL:EXT:tt_address/pi1/locallang_ff.xml:pi1_flexform.sortOrder.ascending</numIndex>
										<numIndex index="1">ASC</numIndex>
									</numIndex>
									<numIndex index="2" type="array">
										<numIndex index="0">LLL:EXT:tt_address/pi1/locallang_ff.xml:pi1_flexform.sortOrder.descending</numIndex>
										<numIndex index="1">DESC</numIndex>
									</numIndex>
								</items>
								<default></default>
							</config>
						</TCEforms>
					</sortOrder>

**Comment by marcobiedermann** [comment]
I would like to sort addresses manually. Currently they are renderes ASC by last name.
Rearranging them in datalist selection in TYPO3 backend does not work.

**Comment by BastianBalthasarBux** [comment]
Has been resolved with the new extbase/fluid based plugin.
Please switch to that, we won't fix the old pibase code anymore, as it is supposed to be deprecated.
