### ISSUE TITLE
display categories in address item

### ISSUE THREAD

**Issue by Hogego** [FriendsOfTYPO3/tt_address#260]
Hi, i am not sure if this is the right place for this question!?
In the new fluid-based-version of tt_address I would like to display the categories that are listed to the address entry in the FE.
In former versions I used ###GROUPLIST### for this. Any hints?
Thanks a lot
Hoge

**Comment by georgringer** [comment]
you can iterate over `{address.categories}` to get all categories

**Comment by Hogego** [comment]
may i ask again?
Putting this in a template - for example in ListItem.html - I get an error like 1273753083: Cannot cast object of type "TYPO3\CMS\Extbase\Persistence\ObjectStorage" to string. 

What is the correct way to generate the output of the given categories to each address in the FE?

thank you
Hoge
> Am 29.10.2019 um 21:12 schrieb Georg Ringer <notifications@github.com>:
> 
> {address.categories}

**Comment by georgringer** [comment]
You need to iterate over the objects and output eg the title

**Comment by Hogego** [comment]
Hi Georg,

I dont get it to work:

		<f:if condition="{address.categories}== 1">
			<f:then>
			Fächer: {sys_category.title} 
			</f:then>
			<f:else>
				<f:if condition="{address.categories} == 0">
					<f:then>
						Leer
					</f:then>
				   <f:else>
					   k.A.
				   </f:else>
				</f:if>
			</f:else>
		</f:if>

could you tell me please what is wrong here
there is still no output of the Category Title

thanks again

Hoge

**Comment by georgringer** [comment]
```
<f:if condition="{address.categories}">
<f:for each="{address.categories}" as="category">
  {category.title}
</f:for>
</f:if>
```
