### ISSUE TITLE
Missing \ at "Updating from...." docu

### ISSUE THREAD

**Issue by Teisi** [FriendsOfTYPO3/tt_address#264]
Missing "\\" after sDISPLAY.settings at the docu  updating from 3.x to 4.0.0 - [Link to the docu]
(https://docs.typo3.org/typo3cms/extensions/tt_address/stable/Administration/Updating/Index.html)

Line:
"Add TSconfig TCEFORM.tt_content.pi_flexform.ttaddress_listview.sDISPLAY.settings.displayMode.addItems.my_template = My Template"

Should be like:
"Add TSconfig TCEFORM.tt_content.pi_flexform.ttaddress_listview.sDISPLAY.settings\\.displayMode.addItems.my_template = My Template"

Maybe cause of escaping?!

**Comment by georgringer** [comment]
Wanna add a pr?

**Comment by Teisi** [comment]
done : https://github.com/FriendsOfTYPO3/tt_address/pull/267

I thought it would be easier with the small stuff if you did it yourself... :)

**Comment by georgringer** [comment]
it is far less work if I just click merge instead of doing it myself ;) thx
