### ISSUE TITLE
Localization for non-Admin-Users fails

### ISSUE THREAD

**Issue by Schwamo** [FriendsOfTYPO3/tt_address#265]
## Bug Report

**Current Behavior**
If a non admin-user tries to localize a tt_address-entry, localization fails. A new tt_address-entry is created, but it is not connected to the entry in the default language. Also the localization-flag is still available.
As an administrator localization of tt_address-entries works like expected.

**Environment**
- TYPO3 version(s): 9.5.13
- tt_address version: 5.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 10.14.6

**Comment by georgringer** [comment]
Does the editor have access to the l10nparent field?

**Comment by Schwamo** [comment]
Hi Georg, oh, you are right! The field "l10n_parent" in the Address-Section in the Back-User-Group was not set. After I set the field, everything worked as expected. 
So it's not bug, but my mistake :_). 
Thank you!

**Comment by georgringer** [comment]
thanks for checking and your fast feedback
