### ISSUE TITLE
Provide an import_id like in ext:news

### ISSUE THREAD

**Issue by benwalch** [FriendsOfTYPO3/tt_address#266]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When importing tt_address from external sources, it would be nice to have a field to identify already imported records.

**Describe the solution you'd like**
* An additional field in the database: `import_id`, preferably a `varchar` with a length of **more than 32 characters** (to be able to store GUIDs)
* the import ID field should be declarated as `KEY` in the database
* Getters and Setters on the address Model for this field

**Describe alternatives you've considered**
Any unused text-based field could be used as a workaround (e.g. "skype" field)

**Teachability, Documentation, Adoption, Migration Strategy**
Users can use this field to identify already imported records

**Comment by georgringer** [comment]
I am not so sure about that. @bmack what do you think?

You can extend the db very Easily and if you need an import, you need the importer code anyway...

**Comment by bmack** [comment]
Hey Ben,

I'd recommend building a tt_address importer extension. Having a field that is not in use in tt_address itself seems a lot of load when it's not in use. Extending model + DB should be fairly trivial to do in a custom extension. If you need support on that, let me know.

Benni!

**Comment by benwalch** [comment]
Hi, 

true. Already extended the Model + DB in my custom extension. Thats not a problem. I was just wondering because in EXT:news these DB fields with getters/setters in the model are defined out-of-the box (yes, there's an import service ...)
I am using EXT:external_import (great extension by the way..) for importing/syncing tt_address records from an external source, so there's no need for an importer code here. Seemed a little overhead for me to create a custom ext for only adding two additional DB fields with the model - would be more convenient if the extension would provide these DB fields...

Anyway, I understand that adding additional columns to the table which are not used most of the time, affects the performance. So its fine for me.
