### ISSUE TITLE
Image TCA overrideChildTca causes 500 Error when adding image

### ISSUE THREAD

**Issue by ceekay73** [FriendsOfTYPO3/tt_address#270]
## Bug Report

**Current Behavior**
I'm getting a red error box in BE (top right) Error 500 when adding an image to tt_address record.

**Expected behavior/output**
Image added with possibilty to open crop mask, since in TCA there is overrideChildTca and sys_file_refrence.imageoverlayPalette added

**Environment**
- TYPO3 version(s): 9.5.13
- tt_address version: [e.g. 5.0.0]

**Possible Solution**
The 500 Server Error could be linked to the protocol and says "...index.php?route=%%2Fajax%%2Frecord%%2Finline%%2Fcreate&token=--AnonymizedToken--" which is a bug reported on forge.typo3 reportet to be fixed.

As soon as I remove overrideChildTca in TCA in the image part and upload it for testing, I'm not getting the error (but also not the wanted overlay palette.

**Additional context**
I actually came across this error when trying to add the overlay palette to the fe_user tca. to get cropping options for fe_user images. There the same error happens and I thought to have a look at how tt_address handles it - but as I said, same error...

So I think this is more related to the core, but maybe someone can at least reproduce it.

**Comment by BastianBalthasarBux** [comment]
I cannot see any error with tt_address v 5.1.x and TYPO3 v 9.5.15++ when adding images, or cropping them within tt_address ...
Could you maybe give it another try?
And if the error still exists, maybe you could add that link to the forges bug report for further investigation.

**Comment by georgringer** [comment]
I guess this is related to https://forge.typo3.org/issues/91217. so an update to 9.5.16 should fix it. @ceekay73 please check with the latest TYPO3 core

**Comment by ceekay73** [comment]
Thanks fore the feedback - however, my reported issue can be closed. The mentionend error came because of an formatting error in the pageTS. Unforntunately I fogot to report back.

**Comment by BastianBalthasarBux** [comment]
Great. Thanks.
