### ISSUE TITLE
Howto use tt_address inside of custom extension

### ISSUE THREAD

**Issue by danielkoch** [FriendsOfTYPO3/tt_address#273]
In a TYPO3 v6 project I used the following code inside my custom extension:

1. to fetch a `tt_address` record and 
2. Display record by using the `tt_adress` extension (configuration, template)

```
...
$aO = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('tx_ttaddress_pi1');
$aO->cObj = clone $this->cObj;
$conf = $GLOBALS['TSFE']->tmpl->setup['plugin.']['tx_ttaddress_pi1.'];
$conf['singleSelection'] = $this->internal['currentRow'][$fN];
$out = $aO->main('',$conf);
...
```

How is this possible with `tt_address` version `5.x`?

**Comment by Teisi** [comment]
1.: I would say you can use the AddressRepository to retrieve the records.
2.: this should work i think (in your own controller action): https://api.typo3.org/9.5/class_t_y_p_o3_1_1_c_m_s_1_1_extbase_1_1_mvc_1_1_controller_1_1_abstract_controller.html#a188e65541c75d860896b57e2978baaa5

**Comment by danielkoch** [comment]
Thanks for the hints!
