### ISSUE TITLE
Error when editing record, changes are not saved

### ISSUE THREAD

**Issue by erru0000** [FriendsOfTYPO3/tt_address#281]
## Bug Report

**Current Behavior**
When editing an address record and making changes to that, after saving TYPO3 shows this error and does not save the changes:
	
Oops, an error occurred!
An exception occurred while executing 'SELECT `uid`, `l10n_state`, `sys_language_uid`, `l10n_parent` FROM `tt_address` WHERE (`uid` IN (?)) AND ((`tt_address`.`deleted` = 0) AND ((`tt_address`.`t3ver_wsid` = 0) AND (`tt_address`.`t3ver_oid` = 0)))' with params [1]: Unknown column 'l10n_state' in 'field list'

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'SELECT `uid`, `l10n_state`, `sys_language_uid`, `l10n_parent` FROM `tt_address` WHERE (`uid` IN (?)) AND ((`tt_address`.`deleted` = 0) AND ((`tt_address`.`t3ver_wsid` = 0) AND (`tt_address`.`t3ver_oid` = 0)))' with params [1]: Unknown column 'l10n_state' in 'field list' | Doctrine\DBAL\Exception\InvalidFieldNameException thrown in file myproject/typo3_src-10.4.5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 60. Requested URL: http://myproject/typo3/index.php?route=%%2Frecord%%2Fedit&token=--AnonymizedToken--&edit%%5Btt_address%%5D%%5B1%%5D=edit&returnUrl=%%2Ftypo3%%2Findex.php%%3Froute%%3D%%252Fmodule%%252Fweb%%252Flist%%26token%%3D96337079b4aa7bf817337decca4395ca6cf6eb0e%%26id%%3D89%%26

**Expected behavior/output**
changes in address record should be saved and it should show the list of addresses not the error screen

**Environment**
- TYPO3 version(s): [10.4.5]
- tt_address version: [5.1.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Linux-Server]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
can you do a DB compare in the install tool, the field should then be there

**Comment by erru0000** [comment]
so easy, thank you very much!!!
