### ISSUE TITLE
Missing l10n_state in database

### ISSUE THREAD

**Issue by joka123** [FriendsOfTYPO3/tt_address#282]
## Bug Report

**Current Behavior**
when saving an entry the second time i get the error
An exception occurred while executing 'SELECT `uid`, `l10n_state`, `sys_language_uid`, `l10n_parent` FROM `tt_address` WHERE (`uid` IN (?)) AND ((`tt_address`.`deleted` = 0) ...

the sql query on composer installation could not be executed i did it manually

i added the missing field also manaully
ALTER TABLE `tt_address` ADD `l10n_state` TEXT NOT NULL AFTER `l10n_diffsource`; 
and no it's fine

in the extension config i deactivted 
basic.readOnlyNameField

**Environment**
- TYPO3 version(s): 10.4.5
- tt_address version: 5.12.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS:gento linux

**Comment by BastianBalthasarBux** [comment]
This is not a bug of tt_address. The l10n_state field should be generated automagically by TYPO3 core. (and is so in all of my setups)

See this feature: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.3/Feature-85160-AutoCreateManagementDBFieldsFromTCACtrl.html

You should maybe try to re-run the DB-compare wizard in install tool.

Unclear, why the sql-query during composer installation could was not executed correctly.

Maybe it has to do with this (resolved) bug: https://forge.typo3.org/issues/80271

It has ABSOLUTELY NOTHING to do with "basic.readOnlyNameField" in ext-settings.
