### ISSUE TITLE
 SiteNotFoundException on edit tt_address records: No pseudo-site found in root line of page xy

### ISSUE THREAD

**Issue by devmes** [FriendsOfTYPO3/tt_address#293]
## SiteNotFoundException on edit tt_address records: No pseudo-site found in root line of page xy

**Current Behavior**
If you edit an tt_address record (with a record uid that not exists as page uid, for example 100000000), then you recieve a Exception "(1/1) #1534710048 TYPO3\CMS\Core\Exception\SiteNotFoundException - No pseudo-site found in root line of page 100000000".

**Environment**
- TYPO3 version: 9.5.20
- tt_address version:5.1.2
- Is your TYPO3 installation set up with Composer (Composer Mode):yes
- OS: ubuntu 18

**Possible Solution**
In the TCA configuration for the SLUG field is set a displayCond: "PseudoSiteTcaDisplayCondition". I think this function is only for page records and must be remove in the tt_address slug field.

**Comment by Schwuuuuup** [comment]
Hi,
I also wrote in #tt_address on slack, but I don't know if this is really used.

I tried the patch from the pull request and it works for me.
But I have to patch numerous Instances, so it would be great to see this fix making its way into the TER real soon

**Comment by benwalch** [comment]
> Hi,
> I also wrote in #tt_address on slack, but I don't know if this is really used.
> 
> I tried the patch from the pull request and it works for me.
> But I have to patch numerous Instances, so it would be great to see this fix making its way into the TER real soon

same here

**Comment by rfc2822** [comment]
I can confirm that the patch is working here (Typo3 9.5.21; editing tt_address records stopped working with one of the latest bugfix releases), thanks!

**Comment by Patta** [comment]
I also can confirm, that tt_address is working again with TYPO3 9.5.21 with this patch. Please release a bugfix version. many thanks
