### ISSUE TITLE
Treeview Missing

### ISSUE THREAD

**Issue by Evilmachine** [FriendsOfTYPO3/tt_address#3]
Hi,

since the Update the treeview is missing

include_once(/var/www/vhosts/xxx.de/httpdocs/typo3conf/ext/tt_address/class.tx_ttaddress_treeview.php): failed to open stream

Is there any Document that shows how to migrate to version 3?

**Comment by bmack** [comment]
The extension now uses the native category selection (TcaTree) from the core so this code is not needed anymore, no need to keep this code. How did you include this code? In your own extension?

**Comment by BastianBalthasarBux** [comment]
As @bmack already stated: tt_address uses native sys_categories since a while. For that reason, and because we go no more feedback since April (!!) we will close this issue.
