### ISSUE TITLE
Locallang in TCA not fully TYPO3v10 compatible

### ISSUE THREAD

**Issue by jokumer** [FriendsOfTYPO3/tt_address#304]
## Bug Report

**Current Behavior**
Entries in backend can not see field name and predefined items for field sys_language_uid

**Expected behavior/output**
Field name should appear in editors prefered language, at least in default (english).

**Environment**
- TYPO3 version: 10.4.6
- tt_address version: 5.1.2
- Composer Mode): yes
- OSX 10.15

**Possible Solution**
Use switch for core/language extension as already defined in TCA file.

**Comment by georgringer** [comment]
resolved, closing issue
