### ISSUE TITLE
email field has no trim

### ISSUE THREAD

**Issue by bucheggerOnline** [FriendsOfTYPO3/tt_address#306]
hi georg,
hi guys,

could you maybe set a eval => '**trim**,email' to the email field as default?
sometimes when you copy email-adresses you copy a space, that would help. I overwrite that now, but I guess there are as well others who would be happy about that.

thx a lot & kind regards,
matthias

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by bucheggerOnline** [comment]
done ;)
