### ISSUE TITLE
Flexform settings that can be overwritten through TypoScript aren't used anymore

### ISSUE THREAD

**Issue by hannesbochmann** [FriendsOfTYPO3/tt_address#308]
## Bug Report

**Current Behavior**
If you select a sort order in the flexform for example it won't be used. This is due to the way the flexform settings are overwritten with TypoScript settings. In FriendsOfTYPO3\TtAddress\Utility\TypoScript::override() line 42 it is checked if a flexform setting equals to 0 if casted to an integer. For settings which contain strings this is always true. So the sort order for example is always overwritten as long as the setting is present in the TypoScript settings. As the default TypoScript has the sort order set to an emtpy string this is always used.

**Expected behavior/output**
Flexform settings should not be overwritten if not empty.

**Environment**
- TYPO3 version(s): 10.4.8
- tt_address version: 5.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**
Remove the empty settings from TypoScript which can overwrite flexform settings. This would be singlePid, pages, recursive,  sortBy, sortOrder, groupsCombination. Or check if a flexform setting can be interpreted as integer before checking if the integer value equals 0.

**Comment by esokoll2** [comment]
Same here.
Sorting by flexform was broken.
As a Quickfix we added "settings.sortBy" via TypoScript

**Comment by Patta** [comment]
I can confirm. sorting e.g. by organization is not working anymore.
