### ISSUE TITLE
Sorting by plugin does not work

### ISSUE THREAD

**Issue by MarkusBausK** [FriendsOfTYPO3/tt_address#312]
## Bug Report

Sorting of records by plugin for the frontend does not work in my case. No matter what I choose inside the plugin ("sort by" select). Changing of sorting only works by typoscript.

**Environment**
- TYPO3 version(s): 9.5.22
- tt_address version: 5.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux, Mittwaldserver

**Comment by Schwuuuuup** [comment]
This is already fixt in GIT Master version
