### ISSUE TITLE
BE list view performance super slow

### ISSUE THREAD

**Issue by stoppeye** [FriendsOfTYPO3/tt_address#315]
## Bug Report

**Current Behavior**
When I select a folder that contains 274 addresses (and no other records) in list view, it takes ~12-13 seconds for the 20 preview records to be displayed. If you then click the top bar to show all records, it will take ~45 seconds to display the first page with records. Strictly speaking, this might not be a bug, but the performance is so terrible that it basically becomes unusable, when you have to edit a number of addresses in the BE.
It doesn't make a difference whether the field "contains plugin" in the folder's page properties is set to "Address" or not.
The table tt_address in this TYPO3 installation contains ~40'000 records overall, but the specific PID in the example above just 274.

**Expected behavior/output**
The list view should display tt_address records within 1-3 seconds. Other folders in the same installation, which have similar parameters (250 - 300 records by PID, between 45'000 and 90'000 records overall per record type), have no problems and are displayed within very few seconds. In general, this TYPO3 installation hasn't got performance problems. It seems that it's really just the folders with tt_address records.

**Environment**
- TYPO3 version: 9.5.22
- tt_address version: 5.2.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Linux
- MySQL: 8.0.20

**Additional context**
We just upgraded from TYPO3 9.5.18 and tt_address 4.3.0 to the versions mentioned above (we then had to upgrade tt_address, because of #294). I can't give you any measurements for the old setup, because we never had these kinds of performance issues (and thus no reason the make measurements...).

**Comment by georgringer** [comment]
I never had such issues to be honest. Is it possible to get access to a test installation to test stuff? Otherwise I would recreate a setup myself.

Did you also test this on an empty installation on different server to check if any other extension, script, ... causes the troubles?
