### ISSUE TITLE
display all Adressitems for a category

### ISSUE THREAD

**Issue by rojimtc** [FriendsOfTYPO3/tt_address#316]
## Bug Report

**Current Behavior**
I am not sure how to display all the items for a category on an itempage in the fluid template

**Expected behavior/output**
I have a category with many Items and would like to list on an item page, all the other items for the category. 

**Environment**
- TYPO3 version(s): [9.5.22]
- tt_address version: [5.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
This doesn't work out of the box. I suggest a custom viewhelper which then returns the objects which can be rendered. if you need support for such VH, please contact me via mail or slack (preferred).
As nothing will be changed in the extension I will close this issue.

**Comment by rojimtc** [comment]
Thanks for your reply. i will check and contact. Thanks again.
