### ISSUE TITLE
Remove redundant interface section

### ISSUE THREAD

**Issue by helsner** [FriendsOfTYPO3/tt_address#317]
Out of v10 Upgrade Wizard TCA Migration section:

The 'tt_address' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed

**Comment by georgringer** [comment]
As this is v10 only I propose a TCA/Overrides/tt_address.php and unset it there if version is 10 or wait until v9 is EOL and next major version of tt_address drops support for 9

**Comment by georgringer** [comment]
solved in branch 10-11, therefore closing this one
