### ISSUE TITLE
Sort Adressitems by day

### ISSUE THREAD

**Issue by rojimtc** [FriendsOfTYPO3/tt_address#319]
## Bug Report

**Current Behavior**
i have some contacts in the extension and i can list and sort it by birthday. 
Currently it is sorting by date/year. I would like to sort by **day**.

example entries: 

- user a has birthday 05.01.1980
- user b has birthday 23.01.1986
- user c has birthday 31.01.1950
- user d has birthday 10.01.2010

sorting this list by birthday (ASC) gives this list

1.  user c  birthday 31.01.1950
2.  user a  birthday 05.01.1980
3.  user b  birthday 23.01.1986
4.  user d birthday 10.01.2010

**Expected behavior/output**
I would like to sort the list by **day** and not by date . The expected list is:

1.  user a  birthday **05**.01.1980
2.  user d birthday **10**.01.2010
3.  user b  birthday **23**.01.1986
4.  user c  birthday **31**.01.1950

**Environment**

- TYPO3 version(s): [9.5.22]
- tt_address version: [5.2]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Windows 10]

**Possible Solution**

**Additional context**
Add any other context about the problem here

**Comment by georgringer** [comment]
Thanks for creating this feature request. This is doable within a custom extension which adds another field holding only day and month. The field is synchronized by using a hook of the datahandler.
If you need support, please contact me in private via mail or slack. I won't add that to the extension, hope you understand

**Comment by rojimtc** [comment]
thank you. i will try that way and will contact if necessary.
