### ISSUE TITLE
Adding new Channels to Social Networks

### ISSUE THREAD

**Issue by bh-teufels** [FriendsOfTYPO3/tt_address#320]
## Feature Request
Adding xing and instagram to possible Social Network Chanel

**Comment by karliwalti** [comment]
I was facing a similar challenge. According to the manual, the recommended approach is to use EXT:extender:
https://docs.typo3.org/p/friendsoftypo3/tt-address/5.3/en-us/Development/ExtendTtAddress/Index.html

**Comment by georgringer** [comment]
closing this issue as there is an easy way to extend it
