### ISSUE TITLE
[FEATURE] Add the possibility to create a "location record"

### ISSUE THREAD

**Issue by Teisi** [FriendsOfTYPO3/tt_address#339]
## Feature Request location record
Please add the possibility to create a "location record" and not only a "person record".

Currently, tt_address refers to persons and not to addresses in general (locations).
Which causes one or the other problem when extending, e.g. "crtl->title, label, searchFields" and so on.

Locations would have more or less the same fields except for gender - date of birth - first_name - middle_name - last_name - title.
This is why I think it would fit very well with this extension to offer something like this.
All other fields, list-/show-Plugin would be the same...

I have already played a little bit because of a PR... :
It would be nice if ideally there would be two TCA's, one for people and one for locations - with the same tt_address DB table.
As far as I know, this is only (in my opinion) unattractively possible via the "tx_extbase_type" field, right?
Would this make any sense at all, or is there no way around a separate table (for example tt_locations) here - to make it clean and more extendable?

Thank you!

**Comment by georgringer** [comment]
Thanks for creating the issue! I would like to keep tt_address as simple as possible. The main reason is that it is impossible to cover every required feature customers can think of and this needs some custom code anyway. Every code added makes it harder to maintain the extension which would hit everyone - even the ones who use a small subset.

What I could imagine is a feature to change the label issue per sys_folder which would already help a lot but there won't be a  `tt_location`. 

I hope you can understand that and I will close this issue.
