### ISSUE TITLE
Feature: Use Extbase & Fluid

### ISSUE THREAD

**Issue by christophlehmann** [FriendsOfTYPO3/tt_address#34]
It would be really nice to be able to use fluid templates and there is a PR, see 

https://github.com/FriendsOfTYPO3/tt_address/pull/19

Can someone give Feedback?

**Comment by BastianBalthasarBux** [comment]
I am currently working on this. More exact: I am writing a solution based on the PR, which is not applying CGL and missing some features.

**Comment by christophlehmann** [comment]
Need help? Release date? ;-)

**Comment by BastianBalthasarBux** [comment]
hehe, releasedate .... february 2017? ;) - just kidding - but yes, i wanted to release it earlier. i plan this now for first half of april. work is already in progress, but there are some rough edges i need to polish up ...

**Comment by Seoman77** [comment]
perhaps it's possible to integrate a single/list-View feature, so that you can click on a details-link in the address-list to get a detailed view with perhaps other fields display and another view than in the list view?

**Comment by BastianBalthasarBux** [comment]
@Seoman77 Something like this: https://github.com/BastianBalthasarBux/tt_address ?
;)
(**ATTN:** yet not tested carefully, but testers are welcome!)

**Comment by marvinhuebner** [comment]
Any Updates on this? Would it be helpful to test @BastianBalthasarBux current [master](https://github.com/BastianBalthasarBux/tt_address)?

**Comment by BastianBalthasarBux** [comment]
Hi Marvin, testing of my master would indeed be helpful!
Plans for my master are: Bugfixing and integration of Mapview by end of july/beginning of August (starting with that work by mid of july)

**Comment by Teisi** [comment]
hey,
@BastianBalthasarBux master - last update was a few months ago - 
so are there news about that?

Thx.

**Comment by bmack** [comment]
Hey @Teisi - we are currently cleaning up the original plugin to be v7+ compatible, next step will be to merge that in. will tackle that the next few days.

**Comment by DanielRuf** [comment]
Awesome, I'm looking forward to the next release =)

**Comment by Seoman77** [comment]
Is there also a plan for the Typo3 V8 compatibilty?

**Comment by DanielRuf** [comment]
> Is there also a plan for the Typo3 V8 compatibilty?

It should be already compatible.
https://github.com/FriendsOfTYPO3/tt_address/blob/master/ext_emconf.php
https://extensions.typo3.org/extension/tt_address/

**Comment by Seoman77** [comment]
Hmm, unfortunately i gt a render-error on my version 8, with the same settings and Extension like in Version 7.6. [http://neu.bc-arolsen.de/der-verein/der-vorstand/](url)
i thought, this could be a version problem in version 8. Any Ideas?

**Comment by DanielRuf** [comment]
@Seoman77 is this related? https://forge.typo3.org/issues/75306

**Comment by DanielRuf** [comment]
I see no reference of for renderMode in the repository.

https://github.com/FriendsOfTYPO3/tt_address/search?utf8=%E2%9C%93&q=renderMode&type=

Are you sure that it comes from the unchanged extension? For me the stacktrace says that it is coming from one of your templates.

**Comment by Seoman77** [comment]
I copied everything from the old installation to the new one, so normally it couldn't be a template issue, i think. And the error is gone, if i deactivate the tt_address (Ext/Fluid) plugin.

**Comment by BastianBalthasarBux** [comment]
@Seoman77 the 'official' version does not have any extbase/fluid plugin. Did you use my fork? If so, there was a small bugfix back in june, removing deprecated attribute from flashmessage viewhelper:
https://github.com/BastianBalthasarBux/tt_address/commit/2d351b092096510f49403d039795b1af764b912d

**Comment by Seoman77** [comment]
Yes, i indeed use your fork. but your bugfix doesn't solve my problem. I try to sort it out tonight and you you a feedback.

**Comment by Seoman77** [comment]
will your fork will be reunited with the master?

**Comment by BastianBalthasarBux** [comment]
1. Did you copy the original templates for customization? Look if you applied the change for flashMessage there too.

2. Yes, the extbase/fluid part will go definitively into upstream, as well as multilanguage preparations, @bmack is working on that, I am in contact with him on a more or less regular base.

**Comment by Teisi** [comment]
Question:
will there be a detail and a listview?

If you need a beta tester, im here... :)

**Comment by BastianBalthasarBux** [comment]
@Teisi there is already. Not perfect but ok. Just give it a try, my fork is publicly available ... ;)
I have also issues opened over there, if you find something. I use it myself quite a time now in "semiproduction" (something between integration and production ....), but not super-excessive, so yes, beta-testing is welcome: https://github.com/BastianBalthasarBux/tt_address

**Comment by DanielRuf** [comment]
Is it planned to provide an upgrade path from the marker based version to the Fluid version?

**Comment by BastianBalthasarBux** [comment]
ATM not planned.
Two things must change: static-includes and Flexform/Plugin.
I could imagine that, if we remove some day in the future the old pibase plugin completely, that we will do some upgradewizard.
As long as the old and the new stay together side by side, this won't make really sense, IMHO.

**Comment by DanielRuf** [comment]
Thanks for the information.

What is the current status of this requested move to Fluid templates and what is currently needed to bring this forward?

This would greatly improve the DX and ease the development with own site / theme extensions which override layouts, templates and partials.

**Comment by BastianBalthasarBux** [comment]
Benni is working on that this week.
Seems he's getting ahead fast.

**Comment by vixe76** [comment]
Any news on this?

**Comment by BastianBalthasarBux** [comment]
Not really. As my fork won't be mergeable anymore, I decided to refork and add my changes manually again, respecting the changes done by Benni. This will happen after #T3BOARD18 ;)

**Comment by BastianBalthasarBux** [comment]
https://twitter.com/t3board

I just finished the slides for my Keynote ... ;)

And yes, I wanted it in very fast. But "someone" wanted some things todo first, although I was ready, and he/she not. ;)
No, no cherry-picking. And too many conflicts, it just makes no sense to rebase. But be sure, I will at least have this basic extbase/fluid thing done fast after #T3BOARD18 (which starts today and is over in one week).
Maybe I manage to do this during the week, but as the organizer I expect not much sparetime ;)

**Comment by DanielRuf** [comment]
Ok, thanks for the information. I'll keep waiting then.

**Comment by MarkusBausK** [comment]
Hi,

maybe does it make sense to talk to the developer of https://extensions.typo3.org/extension/cyz_address/, do a code review and merge it into tt_address? cyz_address is doing what most people want from tt_address and I guess he built the extension only because of the standstill of tt_address. For me always tt_address is the first choice because it is like "core" but for the old marker-stuff there is no way into my projects in 2018... What about sponsoring the code review and a possible merging?

**Comment by DanielRuf** [comment]
https://github.com/cyperfection/cyz_address

**Comment by BastianBalthasarBux** [comment]
Does it have any substantial advantages to my fork?
https://github.com/BastianBalthasarBux/tt_address

**Comment by Teisi** [comment]
For everybody who's interested:
https://extensions.typo3.org/extension/sic_address/

(enable dev mode in the extension manager!)

i think this one is interesting too, i like the BE dev mode module! :)

**Comment by BastianBalthasarBux** [comment]
Addressed in PR #71
