### ISSUE TITLE
 Error Unknown column 'uid' in 'field list' 

### ISSUE THREAD

**Issue by TomQv** [FriendsOfTYPO3/tt_address#350]
## Bug Report

Just installed extension tt_address to use it with ods_osm and now when I go in backend to List-module I see the following error:

Oops, an error occurred!
An exception occurred while executing 'SELECT `uid` FROM `tt_address` WHERE (`tt_address`.`pid` = ?) AND ((`tt_address`.`deleted` = 0) AND ((`tt_address`.`t3ver_wsid` = 0) AND (`tt_address`.`t3ver_oid` = 0))) LIMIT 1' with params [1]: Unknown column 'uid' in 'field list'

**Environment**
- TYPO3 version(s): 10.4.17
- tt_address version: 5.2.1
- OS: Windows 10

Any idea? I want to use tt_address to store locations for markers with 
https://github.com/bobosch/ods_osm/issues/77

Thanks, Tom

**Comment by georgringer** [comment]
this is if the table `tt_address` is extended but the extension is not required in the `ext_emconf.php` file, then the dependency is not resoved properly.
remove the DB table, and 1st install tt_address and then the other exts
