### ISSUE TITLE
.htaccess file contains outdated directives

### ISSUE THREAD

**Issue by sypets** [FriendsOfTYPO3/tt_address#354]
## Bug Report

**Current Behavior**
Resources/Private/.htaccess contains:

```
Order allow,deny
Deny from all
```

This is for older Apache versions  < 2.3 only (or newer versions with compat module).

**Possible Solution**

Change file, as customary in other extensions:

```
# Apache < 2.3
<IfModule !mod_authz_core.c>
	Order allow,deny
	Deny from all
</IfModule>

# Apache >= 2.3
<IfModule mod_authz_core.c>
	Require all denied
</IfModule>

```

## See also

* issue for news: https://github.com/georgringer/news/issues/1543
* PR for news: https://github.com/georgringer/news/pull/1544

**Comment by neufeind** [comment]
+1 from me. Quite a few installations still run with the compat-existension enabled, but that's unclean.
I took the liberty to create a pull-request from your code. Thanks for the suggestion.
