### ISSUE TITLE
"drop index / create index" in install tool (database analyzer)

### ISSUE THREAD

**Issue by seirerman** [FriendsOfTYPO3/tt_address#359]
## Bug Report

**Current Behavior**
When I check the database analyzer in the install tool after installing tt_address I get the following message:
`DROP INDEX 'pid' ON tt_address;`
`CREATE INDEX 'pid' ON tt_address (pid, email);`
This should disappear after running the database wizard, but it keeps popping up and I can't get rid of it through the database analyzer. Reinstalling the extension didn't help.

**Environment**
- TYPO3 version(s): 9.5.30
- tt_address version: 5.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: RedHat Linux

**Additional context**
It's only a minor issue, since the extension seems to be running just fine otherwise.

**Comment by seirerman** [comment]
Yes, the message is gone now.

**Comment by georgringer** [comment]
merged, can be closed
