### ISSUE TITLE
Difference between TER and Packagist

### ISSUE THREAD

**Issue by ayacoo** [FriendsOfTYPO3/tt_address#360]
Hi, just a short question ;-)

We have version 5.3 as the latest version on packagist: https://packagist.org/packages/friendsoftypo3/tt-address
TER latest version is 5.2.1: https://extensions.typo3.org/extension/tt_address/

Is there a specific reason for this? Should the TER not be further supported?

**Comment by georgringer** [comment]
@bmack can you push it to ter?

**Comment by bmack** [comment]
Thanks @ayacoo . 5.3.0 has just been published to TER.
