### ISSUE TITLE
Add stronger typing to AddressController and List Flexform (throws exception if itemsPerPage is empty in Display settings)

### ISSUE THREAD

**Issue by hdnetmaxamann** [FriendsOfTYPO3/tt_address#370]
## Bug Report

Hi there.

**Current Behavior**
Exception:
Argument 3 passed to TYPO3\CMS\Extbase\Pagination\QueryResultPaginator::__construct() must be of the type int, string given, called in /app/public/typo3conf/ext/tt_address/Classes/Controller/AddressController.php on line 266

If the Plugin Options -> Display [settings.paginate.itemsPerPage] is empty the given exception occur.
Its also possible to enter letters instead of numbers.

**Expected behavior/output**
I expect that tt_address plugin won't throw an exception if itemsPerPage is empty in Plugin configuration.
I further expect that it is not possible to enter letters or leave itemsPerPage empty.

**Environment**
- TYPO3 version: 10.4.20
- tt_address version: 5.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**

AdressController.php 
Line: 261 
Change:
`$itemsPerPage = $this->settings['paginate']['itemsPerPage'] ?? 10`
to:
`$itemsPerPage = !empty($this->settings['paginate']['itemsPerPage']) ? (int)$this->settings['paginate']['itemsPerPage'] : 10;`
because the statement will be always true and therefore even an empty string can be set as itemsPerPage.

To harden it even more we could fix the Flexform (List.xml):

Line 282 and following:
Change:
`<eval>trim,intval</eval>`
to:
`<eval>trim,int</eval>`
to get number evaluation and the number field in BE form
and add:
`<default>10</default>`
`<range><lower>1</lower></range>`
to also set the default number in flexforms and add minimum value.

Should I provide a pull request?

Best regards
Max

**Comment by georgringer** [comment]
a default shouldn't be set as there is a fallback from TypoScript and the intcast is already in master IMHO but yeah PR would be great

**Comment by hdnetmaxamann** [comment]
You are right, there is an int cast in the [master](https://github.com/FriendsOfTYPO3/tt_address/blob/f6d895c30dba6073071d5100fc9ff943eaa26ff5/Classes/Controller/AddressController.php#L264) branch.
And a default [TypoScript ](https://github.com/FriendsOfTYPO3/tt_address/blob/f6d895c30dba6073071d5100fc9ff943eaa26ff5/Configuration/TypoScript/setup.typoscript#L69) fallback.
I did not load the tt_address typoscript in my extension so i get this exception because there was no TypoScript fallback (loaded). 🙈 
But the flexform should be hardened anyway.

**Comment by georgringer** [comment]
merged, thx
