### ISSUE TITLE
Defined crop variants don’t apply

### ISSUE THREAD

**Issue by klodeckl** [FriendsOfTYPO3/tt_address#376]
## Bug Report

**Current Behavior**
I defined some crop variants in page tsconfig via TCEFORM.sys_file_reference.crop.config.cropVariants.default but they don’t show in tt_address records. Is this a bug?

**Expected behavior/output**
Defined crop variants should be shown for the image in tt_address records.

**Environment**
- TYPO3 version(s): 9.5.31
- tt_address version: [e.g. 4.0.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Debian 10
- PHP 7.4

**Comment by georgringer** [comment]
just tested it with 
```
 TCEFORM.sys_file_reference.crop.config.cropVariants {
        default {
            title = Default desktop
            selectedRatio = NaN
            allowedAspectRatios {
                NaN {
                    title = free
                    value = 0.0
                }
            }
        }
        specialMobile {
            title = Our special mobile variant
            selectedRatio = NaN
            allowedAspectRatios {
                4:3 {
                    title = ratio 4/3
                    value = 1.3333333
                }
            }
        }
    }
```

and it works fine. as tt_address does simply nothing in that regarding I am pretty sure it is some other issue, maybe invalid tsconfig code with too many `{` or `}`?
