### ISSUE TITLE
Make tt_address availible for LTS 11

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/tt_address#377]
## Feature Request

I would like to use tt_address in LTS 11

**Describe the solution you'd like**
The current master version can already be installed in 11LTS, however the plugin throws errors on including:

`Fluid parse error in template Address_action_list_8a17851681f2498a2d4fd0591b10670d326851bf, line 31 at character 22. Error: The ViewHelper "<f:widget.paginate>" could not be resolved. Based on your spelling, the system would load the class "TYPO3Fluid\Fluid\ViewHelpers\Widget\PaginateViewHelper", however this class does not exist. (error code 1407060572). Template source chunk: <f:widget.paginate objects="{addresses}" as="paginatedAdresses" configuration="{settings.paginate}">`

**Describe alternatives you've considered**
md_news_author already works for 11LTS, however it is to special for my use case

**Comment by neufeind** [comment]
For additional background:
All f:widget.* were deprecated in v10 and removed with v11.
https://docs.typo3.org/other/typo3/view-helper-reference/10.4/en-us/typo3/fluid/latest/Widget/Paginate.html
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.0/Breaking-92529-AllFluidWidgetFunctionalityRemoved.html
Migration of paginate: https://susi.dev/typo3-fluid-paginate

**Comment by linawolf** [comment]
Yeah, the Paginator Api seems already to be implemented. We would only need to drop the old viewhelper

**Comment by georgringer** [comment]
@linawolf the extension itself works fine but I won't drop the old pagination as it works in 10. However I am on it to improve the code to enable the new way automatically if 11 is used
