### ISSUE TITLE
empty "name" field if "first name" and "last name" are being emptied

### ISSUE THREAD

**Issue by TBschen** [FriendsOfTYPO3/tt_address#379]
## Bug Report

**Current Behavior**
If you type something into the "first name" and/or "last name" fields and save, the "name" field will be generated automatically. If you afterwards decide to empty both "first name" and "last name", the "name" field will not be updated (=emptied).

**Expected behavior/output**
I would expect the "name" field to always represent the current combination of "first name" and "last name". So if someone afterwards decides to empty those fields (they're optional afterall), the "name" field should also be empty again.

**Environment**
- TYPO3 version(s): 10.4.21
- tt_address version: 5.3.0

**Comment by georgringer** [comment]
Thanks for the report. This is valid but with upcoming version the auto update of the field has been removed and the field itself will be removed later. Therefore I close this issue.
