### ISSUE TITLE
Please release to TYPO3 repository, where there is still a version that restricts the TYPO3 dependency to 11.3.99

### ISSUE THREAD

**Issue by rowild** [FriendsOfTYPO3/tt_address#381]
## Bug Report

**Current Behavior**
The ext (from ext repository) is not installable (using the Extension manager in legacy installations) on the latest TYPO3 v11.5.x, because the version dependency is set to 11.3.x

**Expected behavior/output**
Being able to install the ext with the latest TYPO 11.5 versions.

**Environment**
- TYPO3 version(s): 11.5.3
- tt_address version: 5.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: OSX 10.15.6

**Possible Solution**
Release the latest github version to the TYPO3 repository

**Additional context**
After installing by accepting the "I know what I do" warning, I did not experience any problems so far.

**Comment by georgringer** [comment]
@bmack just FYI
