### ISSUE TITLE
pagination widget issues in TYPO3 11.5

### ISSUE THREAD

**Issue by exxtrainteractive** [FriendsOfTYPO3/tt_address#385]
Although I see multiple issues here concerning tt_address causing errors in TYPO3 11 (that should be solved and merged to master), I keep getting errors with the current tt_address version 5.3.0. I can not show a single address or address list in the frontend.

The log keeps referring to issues with f:widget.paginate

Do I need another version of tt_address?
Help much appreciated.

TYPO3 version: 11.5.3
tt_address version: 5.3.0
Tested local on MacOS 

Thanks!

**Comment by morange** [comment]
Hi there,
I found a very similar bug. This is the output error message:
`Argument 3 passed to TYPO3\CMS\Extbase\Pagination\QueryResultPaginator::__construct() must be of the type int, string given, called in /var/www/html/public/typo3conf/ext/tt_address/Classes/Controller/AddressController.php on line 266`

TYPO3 version: 10.4.21
tt_address version: 5.3.0
Tested local on MacOS, ddev


Many thanks for your extension (Y)

**Comment by exxtrainteractive** [comment]
Hi,

I had the same error message!
In the meantime we put the site on a staging nginx server and the problem also (or still) exists there. So it's not MacOS or ddev related it seems.

**Comment by georgringer** [comment]
this has been fixed in master, can you crosscheck?

**Comment by exxtrainteractive** [comment]
We now used version #47496ad and it works in TYPO3 11.5! 
Could you please make a release or maybe a tag of this fix, so we can keep the extension up to date? 

Thanks!

**Comment by georgringer** [comment]
will do
