### ISSUE TITLE
save new entry with more then one image

### ISSUE THREAD

**Issue by morange** [FriendsOfTYPO3/tt_address#386]
## Bug Report

**Current Behavior**
I create an new entry with an image of the contact person. After saving i have 2 images – one of the person an an ather one.

**Expected behavior/output**
Only the selected image should be saved.

**Environment**
- TYPO3 v10.4.21
- tt_address: 5.3.0
- Composer: no
- macOS 11.6.1
- docker 20.10.10
- ddev v1.17.7

Many thanx for your work and help
Steffen

**Comment by georgringer** [comment]
thanks for creating the issue! I couldn't reproduce this one. As tt_address does nothing custom regarding backend and TCA this is either an issue on your installation (e.g. having some old sys_file_reference records.
