### ISSUE TITLE
PHP 8 warnings

### ISSUE THREAD

**Issue by dmitryd** [FriendsOfTYPO3/tt_address#387]
## Bug Report

**Current Behavior**

Under PHP 8 there are warnings that break the site:

```
  [ TYPO3\CMS\Core\Error\Exception ]
  Warning: Undefined array key "cache_ttaddress_category" in /var/www/html/web/typo3conf/ext/tt_address/ext_localconf.php line 7

  [ TYPO3\CMS\Core\Error\Exception ]
  Warning: Undefined array key "ttaddress_geocoding" in /var/www/html/web/typo3conf/ext/tt_address/ext_localconf.php line 10
```

**Expected behavior/output**
No warnings.

**Environment**
- TYPO3 version(s): 11.5.4
- PHP: 8.0
- tt_address version: 5.3.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

Replace `is_array` with `isset`.

**Comment by lochmueller** [comment]
Hey @dmitryd 
This is already fixed in the current master: https://github.com/FriendsOfTYPO3/tt_address/commit/f667b1b81330579be882395db87f4fec0034e626
Regards,
Tim

**Comment by dmitryd** [comment]
@lochmueller Thanks! Any news when it will be released? :)

**Comment by lochmueller** [comment]
Hey @dmitryd I don't know... I got the same error and found the issue. So I thought I sent you the short note :) Will be happy, if there will be a new release, so I don't need to use current master anymore, too.
Regards,
Tim

**Comment by georgringer** [comment]
release in ter is a bit behind, @bmack can you take a minute?
I will close the issue

**Comment by dmitryd** [comment]
It would be really great to have this released. Linking to master in prod is not a good thing...

**Comment by georgringer** [comment]
you can link to a commit hash but yes I agree

**Comment by dmitryd** [comment]
> you can link to a commit hash but yes I agree

Yes, this is what I do but it still feels unclean... :(
