### ISSUE TITLE
FEATURE: Provide viewhelper for getCleanedNumber and getWwwSimplified

### ISSUE THREAD

**Issue by JanBartels** [FriendsOfTYPO3/tt_address#389]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to display tt_address-records with a FLUIDTEMPLATE and a dataProcessor like this:

```
20 = FLUIDTEMPLATE
20 {
  templateRootPaths {
     0 = EXT:tt_address/Resources/Private/Templates/
    10 = EXT:my_sitepackage/Resources/Private/tt_address/Templates/Address/
  }
  partialRootPaths {
     0 = EXT:tt_address/Resources/Private/Partials/
    10 = EXT:my_sitepackage/Resources/Private/tt_address/Partials/
  }
  layoutRootPaths {
     0 = EXT:tt_address/Resources/Private/Layouts/
    10 = EXT:my_sitepackage/Resources/Private/tt_address/Layouts/
  }
  templateName = Page
  dataProcessing {
    10 = TYPO3\CMS\Frontend\DataProcessing\DatabaseQueryProcessor
    10 {
      table = tt_address
      as = addresses
    }
  }
}
```
If I want to reuse the original partial Address.html to display the record, the fields cleanedPhone, cleanedMobile and wwwSimplified are not available, as the DatabaseQueryProcessor returns DB-records rather than domain-models. Because of the missing fields/access methods I can't reuse the templates and partials of tt_address.

Example:

Templates/Address/Page.html
```
<f:layout name="Default"/>

<f:section name="main">
    <f:for each="{addresses}" as="address">
        <f:render partial="Address" arguments="{address:address.data}"/>
    </f:for>    
</f:section>
```

Partials/Address.html:
```
<li>
  <i class="fas fa-phone"></i>
    {f:translate(key:'label.telephone')}: <a href="tel:{address.cleanedPhone}">  <!-- cleanedPhone not available on DB-record! -->
      <span itemprop="telephone">{address.phone}</span>
    </a>
 </li>
```

**Describe the solution you'd like**
The partial shall use DB-record fields only. Additional viewhelpers shall format phone numbers and web URLs.

Example:

Partials/Address.html:
```
{namespace myttaddr=JBartels\MySitepackage\ViewHelpers}

<li>
  <i class="fas fa-phone"></i>
    {f:translate(key:'label.telephone')}: <a href="tel:<myttaddr:cleanPhoneNumber value="{address.phone}"/>">
      <span itemprop="telephone">{address.phone}</span>
    </a>
 </li>
```
I've implemented a CleanPhoneNumberViewHelper and a SimplifyWWWViewHelper to format the fields in the same way the original Domain-get-Methods did. If you're interested in this feature, I can provide an implementation of my custom ViewHelpers as PR for EXT:tt_address.

**Comment by georgringer** [comment]
thanks for using tt_address and creating the issue. I am unsure if this should be shipped by the extension. @bmack what do you think?

**Comment by JanBartels** [comment]
For clarity: It's intended to reuse the existing ttaddr namespace for the new VH, of course. My example above still uses my own namespace.

Improved Example:

Partials/Address.html:

```
{namespace ttaddr=FriendsOfTYPO3\TtAddress\ViewHelpers;}

<li>
  <i class="fas fa-phone"></i>
    {f:translate(key:'label.telephone')}: <a href="tel:<ttaddr:cleanPhoneNumber value="{address.phone}"/>">
      <span itemprop="telephone">{address.phone}</span>
    </a>
 </li>
```

My VHs are functionally exact copies of the access methods of the domain model. In effect, there's no change in the resulting output of the templates. I can't see any objectives why the VHs should not be integrated into the ext. Today's implementation without these VHs burdens integrators with unnecessary effort IMHO.

**Comment by georgringer** [comment]
I need to keep the alternative getters anyway for compatibility reasons and using those is the faster and easier to read alternative. Using a ViewHelper is the best solution if dealing with it as a 3rd party extension. So I don't see any burden for integrators currently

**Comment by neufeind** [comment]
Should we maybe "expose" the protected getCleanedNumber() and maybe move it to some utility-class, so someone can create a simple ViewHelper (in their own extension) to use it?

**Comment by georgringer** [comment]
That is my plan but I will ship the vh as well, not much code and easy to upgrade..

**Comment by georgringer** [comment]
@JanBartels wanna take a look at https://github.com/FriendsOfTYPO3/tt_address/pull/391?

**Comment by JanBartels** [comment]
Thanks a lot! The PR looks good for me. The VHs help at least to reduce the effort for custom templates.
