### ISSUE TITLE
images of sys_category are not shown in FE

### ISSUE THREAD

**Issue by schiran** [FriendsOfTYPO3/tt_address#394]
Typo3 11, tt_address master-branch

Add a sys-category with a containing image to a tt_address-record. 

In fluid-Template, check the content of the attached category with f:debug. 
Image (and many other fields of sys-category) don't show up.

When doing the same with tt_news, all fields appear. 

I assume, this is a part of the ongoing task to make the extension v11-ready. 

If it is not too complicated, I could try to provide a patch. 

Any hints?

**Comment by georgringer** [comment]
This is true as https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Domain/Model/Category.php does not cover the fields. I will add the model and change the implementation

**Comment by georgringer** [comment]
Ok i need to close this issue. sys_category doesn't have an images field by default. this comes from ext:news probably. you need an additional extension which provides those fields in the model. see https://github.com/studiomitte/ttaddress_country_relation for an example. if you need help, feel free to contact me, e..g on slack or mail. but won't and can't be part of tt_address
