### ISSUE TITLE
Detail view not empty

### ISSUE THREAD

**Issue by Hobokens** [FriendsOfTYPO3/tt_address#398]
## Bug Report

**Current Behavior**
I put the detail view plugin of tt_address on a page. When I open the page in the frontend, I see all my addresses. I added the detail view on this page just for the action "show" from list view. When I open the page directly, I don't want to see all the addresses.

**Expected behavior/output**
I expect to see nothing when I open the page directly.

**Environment**
- TYPO3 version(s): 10.4.23
- tt_address version: 5.3
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by Hobokens** [comment]
I can "solve" the problem for the moment by setting the startingpoint in the plugin to a page without addresses

**Comment by AstCommodore** [comment]
I stumbled over this issue, too.

In the show action there is and condition to redirect to the current page without any parameters. Therefor the default list action get's called and all addresses are outputted.

```
public function showAction(\FriendsOfTYPO3\TtAddress\Domain\Model\Address $address = null)
    {
        if ($address === null) {
            $this->redirectToUri($this->uriBuilder->reset()->setTargetPageUid((int)$GLOBALS['TSFE']->id)->build());
        } else {
```

I think this isn't a wanted behaviour for a detail view for the most scenarios. Maybe a further version could add an error handling for non given addresses or simply surround the show view by a condition like

```
<f:if condition="{address}">
		<f:then>
```

Greetings,
André
