### ISSUE TITLE
Style selection not working after updating to 3.0.0 (from 3.0.0dev)

### ISSUE THREAD

**Issue by RonMen** [FriendsOfTYPO3/tt_address#4]
Hi.

I run into an issue since the style selection isn't working anymore. I debugged it an there seems to be an issue within the [AbstractFilesToSelector.php (line 37)](https://github.com/FriendsOfTYPO3/tt_address/blob/master/Classes/Hooks/Tca/AddFilesToSelector.php#L37).

So I changed the line from
```
$thePageId = $params['row']['pid'];
```
to
```
$thePageId = $params['flexParentDatabaseRow']['pid'];
```
to get the Template-Files within our fileadmin/... subfolder shown again.
We are not aware if this is the right way, but it seems the first entry isn't providing the page id it should.

Can someone confirm the usage is right or let me know how to change it right?

Regards
RM

**Comment by fischhase** [comment]
Hi Ron,

I can confirm that. Your solution brings template selector to the backend form. 

Thank you
