### ISSUE TITLE
Unknown column 'title_suffix' in 'field list' 

### ISSUE THREAD

**Issue by Hobokens** [FriendsOfTYPO3/tt_address#400]
## Bug Report

**Current Behavior**
Saving an address I get the following error
`An exception occurred while executing 'SELECT `title_suffix` FROM `tt_address` WHERE `uid` = ?' with params [244]: Unknown column 'title_suffix' in 'field list' `

The Analyze Database Structure in the backend is broken. I rebuilt the PHP autoload information and cleared the cache.

**Environment**
- TYPO3 version(s):10.4.23
- tt_address version: 6.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): no

**Comment by georgringer** [comment]
> the Analyze Database Structure in the backend is broken

what does that mean?

**Comment by Hobokens** [comment]
I tried to check the database Structure in the maintenance module, but got the error message that there is a broken extension.

**Comment by Hobokens** [comment]
I close this issue because I can't reproduce it anymore.
