### ISSUE TITLE
docu missing

### ISSUE THREAD

**Issue by premier-lifeboat** [FriendsOfTYPO3/tt_address#401]
Hi
I just noticed that there is a new version available. However - being a major release - I'd like to know upfront if there is anything I have to take care of. Thus it would be great if  
https://github.com/FriendsOfTYPO3/tt_address/blob/master/Documentation/Administration/Updating/Index.rst
will see any update on updating v5.x to v6.x

**Comment by georgringer** [comment]
@sypets or @linawolf could you help?

**Comment by linawolf** [comment]
@georgringer  yes, I ll have a look, please assign me
