### ISSUE TITLE
Adress Detailpages not found in indexed_search

### ISSUE THREAD

**Issue by markussoeth** [FriendsOfTYPO3/tt_address#404]
## Bug Report

**Current Behavior**
Adress data from detailpages can not be found in local search (indexed_search)
Additional content Elements on the detailpages show up in indexed_search, but no adress data.
I can reproduce the problem on several TYPO3 installations.
Also when using standard templates from the extension. 

**Expected behavior/output**
Want to find detailpages of adresses in indexed_search.

**Environment**
- TYPO3 version(s): [11 LTS]
- tt_address version: [6.0.0]
- Is your TYPO3 installation set up with Composer (Composer Mode): [no]
- OS: [Linux]

**Possible Solution**

Maybe the content of the detailpage is not cached?

**Comment by georgringer** [comment]
the view is not cached but I suspect a mixture of the comments `<!--TYPO3SEARCH_end-->` & ` as indexed_search doesn't care from there the content comes but indexes the final HTML
