### ISSUE TITLE
[BUG]: Loading wrong images/files on TYPO3 v8 due to cObject->IMAGE changes

### ISSUE THREAD

**Issue by diealtebremse** [FriendsOfTYPO3/tt_address#41]
With tt_address 3.2.2 and Typo3 8.7.2 I had problems with the images. It seemed that random files (including PDFs etc.) were loaded instead of the corresponding images. I have managed to fix this by replacing  `'data' => 'file:current:uid'` with `'data' => 'file:current:uid_local'` in tt_address/pi1/class.tx_ttaddress_pi1.php line 393.
Is this a bug or did I miss somthing?

**Comment by Teisi** [comment]
same problem here, the fix from @diealtebremse works fine so far.

**Comment by marvinhuebner** [comment]
Same problem here a well. The Fix from @diealtebremse works. 

Is this a common solution? If it is it would be great to get this into the extension.

**Comment by jeemit2007** [comment]
Thanks a lot for patch @diealtebremse .
it works fine in t3 8.7.12 !
tt_address 3.2.2

thanks !!!

**Comment by bmack** [comment]
will do ASAP. You'll have a new version on thursday.

**Comment by hannesbochmann** [comment]
That's great. Thanks in advance.

**Comment by bmack** [comment]
Fixed in 3.2.3 (available on packagist and TER in a few minutes)

**Comment by Patta** [comment]
@bmack v3.2.3 with this bugfix breaks the image rendering in TYPO3 7.6.  I think its better to release the v4.0.0 from current dev-master for >= TYPO3 8.7 only. greets

**Comment by Hawkeye1909** [comment]
This doesn't work in Typo3 6.2.31 (yeah, I know ...) either. Instead with this bugfix the wrong image is shown ...
