### ISSUE TITLE
create a new record with the image of the previously created record

### ISSUE THREAD

**Issue by morange** [FriendsOfTYPO3/tt_address#414]
## Bug Report

**Current Behavior**
When uploading an image to a data set, the image from the previous data set is also inserted. It is then necessary to delete the image after saving the data set.

**Expected behavior/output**
The image of the previously created data record should not be inserted.

**Environment**
- TYPO3 v10 LTS
- tt_address 6.1.0
- TYPO3 Symlink Installation
- OS: [Linux, DDEV]

**Comment by BastianBalthasarBux** [comment]
What's a data set? What do you mean exactly?
Guessing what you could mean:

- you create a new record
- you add an image
- save
- create a new record
- add new image
- and then the image of the previous record is also added?

**Comment by BastianBalthasarBux** [comment]
Ok, no problem, we close. You cloud reopen, if the issue occurs again.
