### ISSUE TITLE
Question: link to contact

### ISSUE THREAD

**Issue by C1aas** [FriendsOfTYPO3/tt_address#417]
Hi together, 

If this is the wrong place to ask a question, I’m sorry.

I would like to have a link somewhere on the Website where I can link a contact. Upon clicking on the link, a new window/site with the contact in detail view will be opened.

Is that already possible?

Thank you for your help.
Claas

**Comment by georgringer** [comment]
I guess you are looking for the linkhandler? checkout the documentation https://docs.typo3.org/p/friendsoftypo3/tt-address/main/en-us/Tutorials/Linkhandler.html

**Comment by georgringer** [comment]
closing issue because of no feedback
