### ISSUE TITLE
Record translation with FAL record(s) fails - Child record was not processed

### ISSUE THREAD

**Issue by Teisi** [FriendsOfTYPO3/tt_address#423]
## Bug Report

**Current Behavior**
Translating a tt_address record with image via modul list fails with error:
"Child record was not processed"
"in ...\typo3_src-11.5.16\typo3\sysext\core\Classes\DataHandling\Localization\DataMapProcessor.php line 645"

**Environment**
- TYPO3 version(s): 11.5.16
- tt_address version: 6.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: CentOS and Windows

**Possible Solution**
maybe same missing TCA - table columns like in news?
https://github.com/georgringer/news/pull/890

[EDITI]: or more this seems to be the same issue (we had previously the records were also on -1 all languages):
https://forge.typo3.org/issues/97178

**Additional context**
How i found the news issue 890:
https://forge.typo3.org/issues/88057

**Comment by BastianBalthasarBux** [comment]
Teisi, could you maybe verify if this still is the case with latest tt_address on v11?

**Comment by georgringer** [comment]
closing this issue as IMO this is more a core issue
