### ISSUE TITLE
Feature: Set overallWrap to stdWrap

### ISSUE THREAD

**Issue by Hawkeye1909** [FriendsOfTYPO3/tt_address#43]
As I don't know if the old issue list is still under observation, I recreate my feature request from here: https://forge.typo3.org/issues/60793.

Current line numbers to change would be [126 and 127](https://github.com/FriendsOfTYPO3/tt_address/blob/master/pi1/class.tx_ttaddress_pi1.php#L126-L127).

**Comment by BastianBalthasarBux** [comment]
Thanks for porting of issue. The old tracker is to be closed, if all issues have been ported ... ;)

**Comment by georgringer** [comment]
the old plugin has been deprecated, nothing will be done thee.
