### ISSUE TITLE
PHP Warning: Undefined array key "groups" in AddressController.php line 157

### ISSUE THREAD

**Issue by peter-neumann-dev** [FriendsOfTYPO3/tt_address#445]
## Bug Report

**Current Behavior**
After updating to TYPO3 v11 and PHP 8.1 I get this error about the array key (like many times in PHP ^8.0)

```
PHP Warning: Undefined array key "groups" in /var/www/html/public/typo3conf/ext/tt_address/Classes/Controller/AddressController.php line 157
```

**Expected behavior/output**
It happens right after creating a list view plugin with a single address inside.

**Environment**
- TYPO3 version(s): 11.5.18
- tt_address version: tested 6.1.0 and 7.0.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: macOS 13.0 (Ventura) with DDEV

**Comment by georgringer** [comment]
wanna do a PR?

**Comment by peter-neumann-dev** [comment]
> wanna do a PR?

I would like to, unfortunately I barely know anything about backend and PHP. I think it would be better that someone else can do it so afterwards there are not more bugs than before 😅

**Comment by peter-neumann-dev** [comment]
@georgringer This #446 fixed it for me, but could you check if that is the right solution, please?
