### ISSUE TITLE
Incompatible with PHP 8.2 (Creation of dynamic property)

### ISSUE THREAD

**Issue by timdreier** [FriendsOfTYPO3/tt_address#452]
## Bug Report

**Current Behavior**
List Plugin throws the following Exception:

```text
PHP Runtime Deprecation Notice: Creation of dynamic property FriendsOfTYPO3\TtAddress\Domain\Model\Dto\Settings::$newPagination is deprecated in /var/www/html/private/typo3conf/ext/tt_address/Classes/Domain/Model/Dto/Settings.php line 33
```

**Expected behavior/output**
List Plugin works :)

**Environment**
- TYPO3 version(s): 11.5.24
- tt_address version: 7.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Docker

**Possible Solution**
Add variable declaration to `Settings.php`:

```php
/** @var bool */
protected $newPagination = false;
```

**Comment by bh-teufels** [comment]
when does the fixed version get tagged so that the fix could pulled over composer?
