### ISSUE TITLE
Inline style and Content-Security-Policy (CSP)

### ISSUE THREAD

**Issue by cstrizzolo** [FriendsOfTYPO3/tt_address#467]
It looks like tt_address uses some inline styles in Resources/Private/Partials/Maps.html:

```
(...) style="width:100%;min-height:300px;">
(...) style="display: none">
```

Unfortunately, inline styles are not allowed by the most restrictive settings available for CSP.

Content Security Policy (CSP) helps to reduce XSS risks on modern browsers by declaring which dynamic resources are allowed to load, therefore it is a relevant security measure to be implemented on web sites wherever possibile. More information i.e. here: https://content-security-policy.com/
More information about CSP and inline styles is available here:

`https://content-security-policy.com/examples/allow-inline-style/`

If I set a restrictive Content-Security-Policy for my TYPO3 frontend by adding the following setting to my TypoScript setup

config.additionalHeaders.10.header = Content-Security-Policy: default-src 'self'

the inline styles in Maps.html become not allowed.

As CSP is an important security feature, it would be nice if tt_address were able to run even with CSP enabled at its more restrictive level. The inline styles should be therefore moved to a static external CSS file.

I might try with a less restrictive CSP policy but this would inhibit most of its advantages, making it almost useless.

Would you mind taking the above into consideration for future developments in order to make tt_address able to run in a more secure environment?

More information is available here:

    https://content-security-policy.com/examples/

Thank you very much for all of your efforts.

**Environment**
- TYPO3 version(s): 11.5.26
- tt_address version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): no
- OS: Oracle Linux 9

**Comment by georgringer** [comment]
I fixed some CSP issues in the backend with TYPO3 v12. Regarding the frontend I am unsure if I should fix it. The templates are more a template to start. I was not sure that those - especially the map view - does fit the requirements of the customers out of the box.

therefore the question: Does adding a new css file with just some basic styles really help as the templating is a job which needs to be done anyway? @cstrizzolo

**Comment by cstrizzolo** [comment]
Dear Georg, thank you for your efforts.
You are probably right. However, if default templates were already CSP-compliant, they would be a better start towards compliant customized templates. Therefore IMHO using a CSS file with basic styles instead of inline styles would be preferable anyway.
