### ISSUE TITLE
typoscript resources wrong(?) parameter (EDIT: aka IMAGE Problem on T3 v8)

### ISSUE THREAD

**Issue by joka123** [FriendsOfTYPO3/tt_address#47]
in typo3 8lts
     in getItemMarkerArray function:
'file.' => array(
                    'height' => $height.'c',
                        'import.' => array(
                            'data' => 'file:current:uid'
                        ),   
gives me the wrong relations, i have to use
'file.' => array(
                    'height' => $height.'c',
                        'import.' => array(
                            'data' => '**file:current:originalUid**'
                        ),   

greetings
jochen

**Comment by BastianBalthasarBux** [comment]
Duplicates #41
