### ISSUE TITLE
Feature: support strings in placeholderImage

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfTYPO3/tt_address#48]
We have a specific use case where we use SVG sprites and we want to use a sprite image as fallback.

For this we have to use some `<svg ...></svg>` as output but so far `placeholderImage` just supports paths.

**Comment by DanielRuf** [comment]
Bump.

**Comment by georgringer** [comment]
the `LegacyPluginController` is marked as deprecated, nothing will happen there anymore.

**Comment by DanielRuf** [comment]
Will this usecase be covered or do we have to fork and implement this?

**Comment by georgringer** [comment]
With fluid I am pretty sure you can achieve all that. Regarding the pibase version, I would go with xclass
