### ISSUE TITLE
Modifying record label in backend does not work (any more)

### ISSUE THREAD

**Issue by responseinformationsdesign** [FriendsOfTYPO3/tt_address#485]
[Modifying record label in backend](https://docs.typo3.org/p/friendsoftypo3/tt-address/8.0/en-us/Configuration/TsConfig/Index.html?highlight=label) does not work (any more) after upgrade to TYPO3 11.5.

- TYPO3 version: 11.5.28
- tt_address version: 7.1.0 or 8.0.1

**Comment by responseinformationsdesign** [comment]
Seems to depend on the selected fields.

Try this Page TsConfig

tt_address {
  label = first_name last_name;building
}

Field "building" is not recognized. No problem with "email". "Phone" doesn´t work either.

**Comment by georgringer** [comment]
Fixed it. as alternative you need to add the fields to ctrl|label_alt. currently there are only the following fields listed: `last_name,first_name,email,pid`
