### ISSUE TITLE
[FEATURE] Add zoom levels to flexform settings

### ISSUE THREAD

**Issue by BastianBalthasarBux** [FriendsOfTYPO3/tt_address#492]
Make zoom levels setting accessible to editors (maybe with a dropdown "auto-calc" and a set of zoom levels) and also make it work with OpenStreetMap. ATM it only works with TypoScript and googmaps.

**Comment by georgringer** [comment]
this can be easily done by extending the flexforms. there are so many configurations which could be set by editor like starting lat/lng. please move that to a custom extension
