### ISSUE TITLE
documentation: use tt_address in own extension

### ISSUE THREAD

**Issue by joka123** [FriendsOfTYPO3/tt_address#495]
## Bug Report

**Current Behavior**A clear and concise description of the behavior.
the example code under https://github.com/FriendsOfTYPO3/tt_address/tree/master/Documentation/Tutorials/UsageOfAddressRepository
is not working under typo3 12

can you update the code - this was really helpful
thanks a lot for your work

**Comment by georgringer** [comment]
fixed the example
