### ISSUE TITLE
TCA: cruser_id obsolete in V12

### ISSUE THREAD

**Issue by stoppeye** [FriendsOfTYPO3/tt_address#500]
## Bug Report

**Current Behavior**
The column `cruser_id` is still present in `Configuration/TCA/tt_address.php`, but not in `ext_tables.sql`. Since `cruser_id` is obsolete in V12 (*Breaking: #98024 - TCA option cruser_id removed*), it will no longer be auto-created during installation of the extension. This leads to a mismatch between columns in TCA and in the database, which can lead to database errors, if an application relies on the TCA of `tt_address`.

**Expected behavior/output**
The columns array in TCA should reflect the actual columns in the database.

**Environment**
- TYPO3 version(s): 12.4.6
- tt_address version: 8.0.1

**Possible Solution**
Remove column `cruser_id` from TCA (or only add it conditionally for V11)

**Comment by georgringer** [comment]
cruser_id is unset in TCA/Overrides, I don't see a problem here

**Comment by stoppeye** [comment]
Yeah, I can see that it gets unset in TCA/Overrides, but it doesn't seem to have the desired effect.

If I do the following in my plugin controller:

```
debug($GLOBALS['TCA']['tt_address']['columns']);
```

Then I get this in FE:

```
array(76 items)
   pid => array(2 items)
   crdate => array(2 items)
   cruser_id => array(2 items)
   tstamp => array(2 items)
   hidden => array(3 items)
   ...
```

As you can see, `cruser_id` is stell there...

**Comment by georgringer** [comment]
Will check
