### ISSUE TITLE
insert record rendering not possible because of missing stdWrap functionality 

### ISSUE THREAD

**Issue by colorcube** [FriendsOfTYPO3/tt_address#508]
in tt_content.php tt_address is registered for "insert record":

`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addToInsertRecords('tt_address');`

But that doesn't work. There's no predefined setup and it's not possible to make that work without changes to the controller.

There are three pull requests to make rendering setup possible: #203 #256 #337 

Funny thing, they all do the same. Maybe one could be merged?

**Comment by georgringer** [comment]
no stdwrap needed, but fixed now
