### ISSUE TITLE
e-mail is no anchor tag if i change the template

### ISSUE THREAD

**Issue by marvinhuebner** [FriendsOfTYPO3/tt_address#51]
If i add a second template and select the new template in the plugin (so not using the default) the e-mail address is no longer rendered as an separate html tag (`<a>`), it is only text.

The new template uses the same code as the default template.  

`EXT:tt_address`: 3.2.2
`TYPO3`: 7.6.22

**Comment by Teisi** [comment]
help something like this:

plugin.tx_ttaddress_pi1 {
  templatePath = {$theme.urls.themeResources}Private/Extensions/tt_address/
  defaultTemplateFileName = default_hcard.htm
  templates {
    default_hcard {
      
      email {
        wrap = <span class="mail">|</span>
        // override = E-Mail
        typolink.parameter.field = email
        required = 1
      }
.
.
.
.

**Comment by georgringer** [comment]
7 is not supported anymore in latest (unreleased version 4) and therefore I am closing this issue.

**Comment by BastianBalthasarBux** [comment]
Additionally this concerns the legacy plugin, which is deprecated.
