### ISSUE TITLE
storeBackwardsCompatName does not work or is completely dropped

### ISSUE THREAD

**Issue by gf-luka** [FriendsOfTYPO3/tt_address#510]
It is still possible to set the options for backwards compatibility in the extension settings (_backwardsCompatFormat_, _readOnlyNameField_, _storeBackwardsCompatName_), but this settings seems not be used anywhere in the code. Has this function been completely removed, but the settings and documentation have not yet been properly updated?

We stumbled upon this, because variable **{name}**  in our template does not show anything, since updating to TYPO3 12 and tt_address ^7.1

**Comment by georgringer** [comment]
yes, the autofill has been dropped, not the field itself, sorry if docs msised

**Comment by infabo** [comment]
I think this needs a cleanup. It still has usages.

https://github.com/search?q=repo%3AFriendsOfTYPO3%2Ftt_address%20readOnlyNameField&type=code
