### ISSUE TITLE
Cannot add new address record in TYPO3 v12 PHP 8.2

### ISSUE THREAD

**Issue by MisterMarlu** [FriendsOfTYPO3/tt_address#511]
## Bug Report

**Current Behavior**
I click on "new record", select the tt-address and get an exception.
![image](https://github.com/FriendsOfTYPO3/tt_address/assets/15226569/b42526ff-cb93-40f6-9bce-bf4d24bf3908)

**Expected behavior/output**
The default edit/create view should appear.

**Environment**
- PHP version: 8.2
- TYPO3 version(s): 12.4.9
- tt_address version: 8.0.2
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Debian

**Possible Solution**
The issue is located in Classes/Hooks/Tca/Label.php line 33. Maybe check if it's a new record or an existing one. For new records the old code should be used, for existing ones the new code should be used.

```php
public function getAddressLabel(array &$params): void
{
    // ...

        if (is_numeric($params['row']['uid'])) {
            $row = BackendUtility::getRecord('tt_address', (int) $params['row']['uid']);
        } else {
            $row = $params['row'];
        }
    // ...
}
```

**Comment by MTeskeIn** [comment]
I've got the exact same issue with the same environment specifications.
