### ISSUE TITLE
Deleting Record results in Error

### ISSUE THREAD

**Issue by calien666** [FriendsOfTYPO3/tt_address#513]
## Bug Report

**Current Behavior**
When deleting a record, the `Hooks\Tca\Label::getAddressLabel` is called and tries to detect the record from the param.
This errors in
```sh
PHP Warning: Trying to access array offset on value of type null in /var/www/html/.Build/public/typo3conf/ext/tt_address/Classes/Hooks/Tca/Label.php line 34
```
with latest 8.0.2. In main branch, the error occurs on line 38.

The Bugfix #512 solving #511 doesn't solve this problem, as a deleted record has a valid numeric uid, but doesn't get fetched by `BackendUtility::getRecord()` as this method normally excludes deleted records.

The issue occurs in PHP >= 8.1 (possibly 8.0, too?), tested in 7.4 without problems.

**Expected behavior/output**
I'm not sure, if the method should execute on deleted records, too, thus I don't have an expected behaviour.

**Environment**
- TYPO3 version(s): 11.5.33, 12.4.9
- tt_address version: 8.0.2 (should be in 7.1, too)
- Is your TYPO3 installation set up with Composer (Composer Mode): both
- OS: ddev setup
- php 8.1

**Possible Solution**
* If record is deleted, just return void
* If label should be generated, work with the `$params['row']` as in #512

**Additional context**
Deleting a record in backend only lets the delete icon spin. Reloading shows, the record was deleted. This bug was discovered while working on sudhaus7/xlsimport and testing for TYPO3 11 functionality after preparing v12 support.

**Comment by georgringer** [comment]
thanks - wanna do a PR?

**Comment by calien666** [comment]
Hi @georgringer
Sorry for responding that late. I would do a PR, but as I wrote above, there are two possible solutions. I don't know, which one you prefer.

**Comment by georgringer** [comment]
TBH I don'T have a real opinion but I guess the 2nd one to be in line with

**Comment by Patta** [comment]
I can confirm this issue with latest release 8.0.3
`Core: Error handler (BE): PHP Warning: Trying to access array offset on value of type null in /var/www/html/vendor/friendsoftypo3/tt-address/Classes/Hooks/Tca/Label.php line 38`

**Comment by calien666** [comment]
Thanks, @georgringer. I will take a look.

**Comment by msollmann** [comment]
Can confirm this too. TYPO3 12.4.11, PHP 8.2.13, tt_address 8.0.3

**Comment by georgringer** [comment]
fixed now
