### ISSUE TITLE
possibility to crop / set the image width / height

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfTYPO3/tt_address#52]
Is it possible to crop / scale the image in the TS?

But I think this is probably obsolete when the Fluid version is released.
https://github.com/FriendsOfTYPO3/tt_address/issues/34

**Comment by BastianBalthasarBux** [comment]
I am not sure if the legacy can do that, but it should. Although we always had some problems with the image rendering.
And indeed the fluid version is able to do that in fluid with the known params.
Take a look here: https://github.com/BastianBalthasarBux/tt_address/blob/master/Resources/Private/Partials/AddressItemDetail.html

**Comment by DanielRuf** [comment]
Bump.

**Comment by BastianBalthasarBux** [comment]
Is obsolete now, with fluid/extbase plugin enabled.
We won't fix legacy code anymore.
