### ISSUE TITLE
Error in TYPO 12.4.14 with console command

### ISSUE THREAD

**Issue by kanow** [FriendsOfTYPO3/tt_address#523]
## Bug Report

**Current Behavior**
Flush cache in cli shows an error:

`PHP Fatal error:  Declaration of FriendsOfTYPO3\TtAddress\Command\GeocodeCommand::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /app/vendor/friendsoftypo3/tt-address/Classes/Command/GeocodeCommand.php on line 47`

**Expected behavior/output**
No error and "Cache flushed" message

**Environment**
- TYPO3 version(s): 12.4.14
- tt_address version: 7.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Docker Container witih PHP 8.2

**Possible Solution**
Can be fixed in line 47 of `FriendsOfTYPO3\TtAddress\Command\GeocodeCommand.php`

just adding that missing `: int`

`protected function execute(InputInterface $input, OutputInterface $output): int`

**Comment by kanow** [comment]
Ah, I see it's already fixed in the master branch. Is fixed in version 8.x. 
Maybe also version 7.x can be fixed? It seems to me that dependencies are not correct in that version.

**Comment by georgringer** [comment]
I don't plan to support the 7.x branch, just patch it yourself or update

**Comment by kanow** [comment]
Ok, did it.
