### ISSUE TITLE
PHP Warning: Trying to access array offset on null

### ISSUE THREAD

**Issue by chrcan** [FriendsOfTYPO3/tt_address#524]
when I delete an address from the folder tt_address 8.0.3 in TYPO3 v12.4.14 I get this warning in the log:

`Core: Error handler (BE): PHP Warning: Trying to access array offset on null in /var/www/html/vendor/friendsoftypo3/tt-address/Classes/Hooks/Tca/Label.php line 38`

could you fix it like this?
I’m not a programmer just by the way !!!

`// Sicherstellen, dass $row['pid'] vorhanden und nicht null ist
if (!isset($row['pid']) || $row['pid'] === null) {
    return;
}

$configuration = $this->getConfiguration((int) $row['pid']);
if (!$configuration) {
    return;
}`

**Comment by georgringer** [comment]
fixed with #513
