### ISSUE TITLE
Wrong label values in backend list (Workspaces)

### ISSUE THREAD

**Issue by rbnzlknb** [FriendsOfTYPO3/tt_address#525]
## Bug Report
If workspaces are active and a label field (`$GLOBALS['TCA']['tt_address']['ctrl']['label_alt']`) of a tt_address record is edited in a non(!) live workspace, this change is not displayed in the backend list (module: web/list), not even in the backend view in the plugin.

The frontend output is correct.

`$GLOBALS['TCA']['tt_address']['ctrl']['label_userFunc'] => \FriendsOfTYPO3\TtAddress\Hooks\Tca\Label::class . '->getAddressLabel';`

I suspect that the workspace overlay is not being accessed here.

If I deactivate the label_userFunc (`$GLOBALS['TCA']['tt_address']['ctrl']['label_userFunc']`) the backend view works as expected.

**Current Behavior**
Im custom-Workspace werden die Eigenschaften aus dem live Workspace angezeigt.

**Expected behavior/output**
The values from the current workspace should be displayed.

**Environment**
- TYPO3 version(s): [12.4.12]
- tt_address version: [8.0.3]
- Is your TYPO3 installation set up with Composer (Composer Mode): [yes]
- OS: [ddev / Linux 6.6.16-linuxkit ]

**Comment by georgringer** [comment]
thanks, fixed
