### ISSUE TITLE
Undefined array key "pages"

### ISSUE THREAD

**Issue by MacGyer** [FriendsOfTYPO3/tt_address#529]
## Bug Report

**Current Behavior**
PHP 8.1 warning of undefined array key "pages" because `$this->settings['pages']` is evaluated without fallback in https://github.com/FriendsOfTYPO3/tt_address/blob/master/Classes/Controller/AddressController.php#L165.

**Expected behavior/output**
No warning/error should be emitted

**Environment**
- TYPO3 version(s): 12.4.x
- tt_address version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Ubuntu 20.04
- PHP Version: 8.1

**Possible Solution**
```
if ($this->settings['pages'] ?? false) {
    $demand->setPages($this->getPidList());
}
```

**Additional context**
none

**Comment by georgringer** [comment]
thanks
