### ISSUE TITLE
Birthday always required in TYPO3 8 [SOLUTION]

### ISSUE THREAD

**Issue by saschaende** [FriendsOfTYPO3/tt_address#55]
You always have to insert a birthday in TYPO3 8, otherwise you get a mysql error with strict mode on.

Solution, if you do not need birthday... overwrite TCA with TCA/Overrides/tt_address.php

`$GLOBALS['TCA']['tt_address']['palettes']['contact']['showitem'] = 'email, --linebreak--,phone, fax, --linebreak--,mobile, --linebreak--,www, --linebreak--,';`

**Comment by Diologenes** [comment]
Hey Sascha my friend and former colleague! 😄 

Another possibility is to disable (and hide) the field via Page TSConfig:
```
TCEFORM {
    tt_address {
        birthday.disabled = 1
    }
}
```
Maybe this is a little bit cleaner for hiding the field and avoid the error... ;-) 

This github-repo has already the correct TCA config (I think):
```
        'birthday' => [
            'exclude' => 1,
            'label' => 'LLL:EXT:tt_address/Resources/Private/Language/locallang_db.xlf:tt_address.birthday',
            'config' => [
                'type' => 'input',
                'renderType' => 'inputDateTime',
                'eval' => 'date',
                'size' => '8',
                **'default' => 0**
            ]
        ],
```

Unfortunately this fixed version is not available on packagist and in TER... ...or am I too stupid to find it?!

**Comment by BastianBalthasarBux** [comment]
Duplicated by issue #55 which has already been resolved.
