### ISSUE TITLE
Fatal Error TtAddressPreviewRenderer in TYPO3 12.4.17

### ISSUE THREAD

**Issue by andyhirsch** [FriendsOfTYPO3/tt_address#553]
## Bug Report

**Current Behavior**
 Fatal error: Declaration of FriendsOfTYPO3\TtAddress\FormEngine\TtAddressPreviewRenderer::renderContentElementPreviewFromFluidTemplate(array $row): ?string must be compatible with TYPO3\CMS\Backend\Preview\StandardContentPreviewRenderer::renderContentElementPreviewFromFluidTemplate(array $row, ?TYPO3\CMS\Backend\View\BackendLayout\Grid\GridColumnItem $item = null): ?string in /var/www/html/vendor/friendsoftypo3/tt-address/Classes/FormEngine/TtAddressPreviewRenderer.php on line 45

**Environment**
- TYPO3 version 12.4.17
- tt_address version: 8.1.0
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: DDEV, PHP 8.1

**Comment by maikschneider** [comment]
See #554
