### ISSUE TITLE
FatalError due to wrong method signature after upgrade to TYPO3 v12.4.17

### ISSUE THREAD

**Issue by o-ba** [FriendsOfTYPO3/tt_address#555]
With https://github.com/TYPO3/typo3/commit/8f07071667fe7a3015cb48678dad013ef024a78a, the method signature of `StandardContentPreviewRenderer.php->renderContentElementPreviewFromFluidTemplate()` method has been changed. Since tt_address overwrites this method in the `TtAddressPreviewRenderer`, the divergent method signature now leads to a FatalError.

**Comment by maikschneider** [comment]
See #554
