### ISSUE TITLE
contact-values (country, city...) from direct_mail_subscription not being saved into tt_address

### ISSUE THREAD

**Issue by Kathara** [FriendsOfTYPO3/tt_address#57]
I have the following setup:

Typo3                                     7.6.15
tt_address                              3.2.2
direct_mail                             5.2.0
direct_mail_subscription        2.0.4

I wanted to add the field "country" to the subscription-page so I added the following to my template:

```
<label for="fe_ttaddress_country_input" id="label-fe_ttaddress_country">Country*</label>
<select class="form_dropdown" name="FE[tt_address][country]" id="fe_ttaddress_country_input" style="text-align-last:center">
     <option value selected disabled>--Choose--</option>
     <option value="inland">some country</option>
     <option value="abroad">others</option>
</select>
```

To my constants as well to my setup on the subscription-page-template I've added the following:

```
plugin.feadmin.dmailsubscription.create.fields = last_name, first_name, title, country, hidden, email, module_sys_dmail_html
plugin.feadmin.dmailsubscription.create.required = title, country, last_name, first_name, email
plugin.feadmin.dmailsubscription.edit.fields = last_name, first_name, title, country, hidden, email, module_sys_dmail_html
plugin.feadmin.dmailsubscription.edit.required = title, country, last_name, first_name, email
```
(I had to add them in both constants and setup; if missing in constants the title is not being saved in tt_address, if missing in setup, the error message "this field is required" is shown on the subscription page.)

The field is being shown but the value from the country-select is not being transmitted to the tt_address table in the database.

With the title I did exactly the same and it works like a charm.

I've seen a solution to this problem (I don't seem to be the only one with this issue) but this would require to install kickstarter and extend the tt_address extension. As I'm quite a freshman to typo3 (especially to the configurations) this seems to be rather difficult when the solution could be so easy.

The issue doesn't only seem to apply to the country field but to almost all fields in the address-group of the contacts-tab from tt_address.

Am I missing something or does this really not work? Is there a way (other than extending the extension) to achieve adding a country to the subscription?

I would be grateful for any pointers or help.

Greetings, Kathara

**Comment by Kathara** [comment]
I have found an easy way to make it happen:

In the file ../direct_mail_subscription/Configuration/TCA/Overrides/tt_address.php I've added "country" to the field list: 

$GLOBALS['TCA']['tt_address']['feInterface']['fe_admin_fieldList'] .= ',title,hidden,gender,name,email,first_name,last_name,company,country';

And now it works.

Wouldn't it be better if there would be listed the whole fields of tt_address which are available?

I'll leave the issue open for the time being. After I receive a feedback from any of the developers, I can still close it.

**Comment by BastianBalthasarBux** [comment]
feInterface is deprecated and removed with TYPO3 v8.
So that may work on your 7.6.15 (as this subscription extension brings an own version of feAdminLib.inc ... buhu, dirty ...) but I am pretty sure not anymore on an up-to-date 8.7.8
Seems like direct_mail_subscription needs some work soon ...

**Comment by georgringer** [comment]
IMO not related to tt_address directly. i am closing this
