### ISSUE TITLE
Introduce site sets for TYPO3 13

### ISSUE THREAD

**Issue by linawolf** [FriendsOfTYPO3/tt_address#570]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Introduce site sets, https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103437-IntroduceSiteSets.html for TYPO3 13

Happy to supply a patch

**Comment by georgringer** [comment]
yeah please go ahead!

**Comment by linawolf** [comment]
There you go
