### ISSUE TITLE
Sort records by order in category

### ISSUE THREAD

**Issue by Hawkeye1909** [FriendsOfTYPO3/tt_address#579]
## Feature Request

I'd like to be able to sort the records by the order within the category relation (tab 'Items') when a category is selected to get the records. This would allow different sorting of the same record depending on which category is used. Also, the records could be in different folders, which usually makes it difficult to sort them uniquely.

Maybe something like [\TYPO3\CMS\Core\Category\Collection\CategoryCollection](https://api.typo3.org/main/classes/TYPO3-CMS-Core-Category-Collection-CategoryCollection.html) could be used...

**Comment by georgringer** [comment]
that is not really possible and I tend not to implement that. feel free to create a custom controller action which does that
