### ISSUE TITLE
Listing of all addresses in an PID

### ISSUE THREAD

**Issue by sbusemann** [FriendsOfTYPO3/tt_address#60]
Added by Fabian Thommen

moved from: https://forge.typo3.org/issues/48949

Now I have to add a single address entry to a address group tho show it in the FE. It should be possible to chose an PID and show all addresses.

Some recherche on the internet showed this was possible befor V2. Now there is only this ugly workaround:

http://forum.typo3.org/index.php?t=msg&goto=305254x%x%

**Comment by BastianBalthasarBux** [comment]
This is possible with version 4.0 and extbase/fluid plugin.
We won't fix legacy code (pibase) anymore, it is supposed to be deprecated.
