### ISSUE TITLE
Cant overwrite email function in typoscript

### ISSUE THREAD

**Issue by M4rt1n17** [FriendsOfTYPO3/tt_address#65]
Hi, I'm pretty new to Typo3 and tried to over write some functions.

1.) I just want this extension to give me the plin text I type in in the fields.
So when I type in (in field Mail) "`info@example.com`" i also want to set the value of the Marker `###EMAIL###` to be "`info@example.com`" and not:
`<a href="mailto:info@example.com" class="email" item="email">info@example.com</a>`

So my question is: how can I overwrite this function in a way which is still working when I update the extension? (editing "ext/tt_address/static/pi1/setup.txt" worked but will get overwritten at the next update)

I already tried overwriting this function by  setting the values to other values in typoscript but it did not work.

`email {}`

`email.typolink.ATagParams = class="btn btm-primary"
email.typolink.parameter.field = normal`

`email.wrap = <a href="mailto:|" class="btn btn-primary"><i class="glyphicon glyphicon-envelope"></i>E-Mail</a>`

2.) Every template gets wraped in a div with the class "`tx-tt_address-pi1`" to avoid this, I also had to edit the Main function.. is there any other way to solve this problem, as It kills my design if there is another div between? Is there maybe a option or a way to overwrite it?

3.) I'm running on Typo3 8.7.15 and Pictures does not get shown in the frontend.. tried many formates (.svg, .png, .jpg..) but none of them get shown in the frontend, even after reinstalling the Extension and resetting the Typoskript. Just made a clean install just to test this, but its not working.

Thank you very much in advance

Best regards,
Martin

**Comment by BastianBalthasarBux** [comment]
One issue per ticket pls.

**Comment by BastianBalthasarBux** [comment]
Additionally: please test current version from this github-repo, with the new extbase/fluid based plugin, which addresses your issues.
The legacy code is still shipped, but:
1. has to be enabled now manually in extension manager
2. should be avoided to be used as it is deprecated and will be removed in a future version!
