### ISSUE TITLE
Image problems after tt_address upgrade 3.2.2->3.2.3 in 7.6.29

### ISSUE THREAD

**Issue by zabinetta** [FriendsOfTYPO3/tt_address#66]
Hello, 
I updated tt_address today and my vcard-Images were gone/mixed in Frontend. Something is not working right.
Most images were gone, one was showing a wrong image. In Backend everything was right.
I reinstalled 3.2.2, and everything was ok again, but maybe it's good to know.
with the best regards,
Sabine

**Comment by bmack** [comment]
Hey sabine,

Which TYPO3 version are you using?

**Comment by zabinetta** [comment]
7.6.29

**Comment by manuelLink** [comment]
can confirm, Images do not work in 7.6
reverting [d2bf6b2](https://github.com/FriendsOfTYPO3/tt_address/commit/d2bf6b22d600b77ee3b115c56307de47e0362a3b#diff-05c23f330e2b6003d4d9d61691b44b60) seems to resolve it

**Comment by andre-spindler** [comment]
I can confirm this.
Same problem. TYPO3 is version 7.6.30.

**Comment by bmack** [comment]
Just released 3.2.4, hope that fixes this issue for you. please test.

**Comment by zabinetta** [comment]
tested, looks good!

**Comment by zabinetta** [comment]
Thank You!
