### ISSUE TITLE
Typo3 9.x compatibility

### ISSUE THREAD

**Issue by rfc2822** [FriendsOfTYPO3/tt_address#67]
The current version tt_address 3.2.3 seems to be incompatible with Typo3 9.3.3:

* not marked as compatible (can be overridden without white page of death)
* when creating a content element, Typo3 takes ages and times out when tt_address is enabled

Are there plans to make tt_address compatible with Typo3 9.x? Maybe I can help.

**Comment by BastianBalthasarBux** [comment]
Hi "Internet Message Format",

yes there are definitively plans, to make tt_address also compatible with TYPO3 v9.
You could help by testing this fork:
https://github.com/BastianBalthasarBux/tt_address
The fork has not been tested right now on v9, but it should work on v8.
[the last big commit which contains all the merging from upstream has also not been tested right now ... so be careful and test on a dev-system, and not in production!]

Not sure if the legacy piBase code will be supported on v9 in any way, personally I have no plans to dive into that code again. ;)

**Comment by BastianBalthasarBux** [comment]
Addressed in PR #71
