### ISSUE TITLE
Change TCA for Mysql strict Mode

### ISSUE THREAD

**Issue by randomresult** [FriendsOfTYPO3/tt_address#68]
When MySQL is in strict Mode, TCA fields need some modifications.
For example the field Birtday needs the following changes:
From:
 `  'eval' => 'date', `

To: 
`  'eval' => 'datetime,int',`

Also there should be a `default => 0` for all fields

At least this has to be done to `birthday` and `sys_language_uid' to make it work on TYPO3 8.7 and MySQL in strict mode which is default from MySQL 5.7

**Comment by neufeind** [comment]
Sounds like that should be adjusted in TYPO3-core instead maybe? Reading about eval in the TCA-documentation it looks like both types should store it as an integer - while you say it does not but auto-converts it in mysql instead?
https://docs.typo3.org/typo3cms/TCAReference/8.7/ColumnsConfig/Type/Input.html#id23

**Comment by randomresult** [comment]
Talked to @ohader - see post here:
https://stackoverflow.com/questions/40542151/typo3-sql-error-incorrect-integer-value-for-column-sys-language-uid-at
Will take care of it.

**Comment by neufeind** [comment]
Thanks. From the thread it seems like empty defaults are the problem here, which eval to int or default=>0 fixes.
