### ISSUE TITLE
3.0.2 Missing comma in TCA => Fatal PHP Error

### ISSUE THREAD

**Issue by cdfre** [FriendsOfTYPO3/tt_address#7]
https://github.com/FriendsOfTYPO3/tt_address/commit/87704e8d446fd7698b8d7ae05482aa0f5f5dcc22

Line 407, after:
` country'`
There has to be a comma!

**Comment by BastianBalthasarBux** [comment]
@cdfre could you please close this issue, as it is resolved with version 3.0.3?
