### ISSUE TITLE
Exception if sort_by is empty

### ISSUE THREAD

**Issue by tillschweneker** [FriendsOfTYPO3/tt_address#81]
If settings.sortBy is not set there is an exception `Unknown column 'tt_address.single_selection' in 'order clause'`.

Tested with TYPO3 9.5.2-dev and tt_address commit ca74c7d

**Comment by georgringer** [comment]
thanks. fixed now

**Comment by tillschweneker** [comment]
Just tested this issue with commit 5213bdb and it works with single selection of addresses. 

When I choose a category or page without defining a sortBy value, the following error occurs `Unknown column 'tt_address.default' in 'order clause'`

**Comment by georgringer** [comment]
Thx will fix tonight, next time just open new issue as it is a new error
