### ISSUE TITLE
$idList must be array for $queryBuilder->createNamedParameter

### ISSUE THREAD

**Issue by tillschweneker** [FriendsOfTYPO3/tt_address#82]
In `FriendsOfTYPO3\TtAddress\Service\CategoryService` #87 the parameter `idList` is a string, but the function needs an array.

**Comment by georgringer** [comment]
I changed now a lot and merged it right now. can you retest it. thanks!

**Comment by neufeind** [comment]
should be fine (verified by reading)

**Comment by georgringer** [comment]
Hehe it is also verified by tests but I still don't use that extension for real, so just included as plugin once ;)

**Comment by tillschweneker** [comment]
fixed! thank you very much!
